// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tips_svr/youme_tips.proto

package YOUMEServiceProtocol;

public final class YoumeTips {
  private YoumeTips() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AppTipsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.AppTips)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint64 tips_id = 1;</code>
     */
    boolean hasTipsId();
    /**
     * <code>required uint64 tips_id = 1;</code>
     */
    long getTipsId();

    /**
     * <code>required bytes channel_id = 2;</code>
     */
    boolean hasChannelId();
    /**
     * <code>required bytes channel_id = 2;</code>
     */
    com.google.protobuf.ByteString getChannelId();

    /**
     * <code>required bytes title = 3;</code>
     */
    boolean hasTitle();
    /**
     * <code>required bytes title = 3;</code>
     */
    com.google.protobuf.ByteString getTitle();

    /**
     * <code>required int32 tips_type = 4;</code>
     */
    boolean hasTipsType();
    /**
     * <code>required int32 tips_type = 4;</code>
     */
    int getTipsType();

    /**
     * <code>required int32 loop_type = 5;</code>
     */
    boolean hasLoopType();
    /**
     * <code>required int32 loop_type = 5;</code>
     */
    int getLoopType();

    /**
     * <code>required bytes content = 6;</code>
     */
    boolean hasContent();
    /**
     * <code>required bytes content = 6;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>required bytes link_keywords = 7;</code>
     */
    boolean hasLinkKeywords();
    /**
     * <code>required bytes link_keywords = 7;</code>
     */
    com.google.protobuf.ByteString getLinkKeywords();

    /**
     * <code>required bytes link_addr = 8;</code>
     */
    boolean hasLinkAddr();
    /**
     * <code>required bytes link_addr = 8;</code>
     */
    com.google.protobuf.ByteString getLinkAddr();

    /**
     * <code>required bytes loop_weekday = 9;</code>
     */
    boolean hasLoopWeekday();
    /**
     * <code>required bytes loop_weekday = 9;</code>
     */
    com.google.protobuf.ByteString getLoopWeekday();

    /**
     * <code>required bytes start_datetime = 10;</code>
     */
    boolean hasStartDatetime();
    /**
     * <code>required bytes start_datetime = 10;</code>
     */
    com.google.protobuf.ByteString getStartDatetime();

    /**
     * <code>required bytes end_datetime = 11;</code>
     */
    boolean hasEndDatetime();
    /**
     * <code>required bytes end_datetime = 11;</code>
     */
    com.google.protobuf.ByteString getEndDatetime();

    /**
     * <code>required uint32 enable = 12;</code>
     */
    boolean hasEnable();
    /**
     * <code>required uint32 enable = 12;</code>
     */
    int getEnable();

    /**
     * <code>required uint64 old_id = 13;</code>
     */
    boolean hasOldId();
    /**
     * <code>required uint64 old_id = 13;</code>
     */
    long getOldId();

    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
     */
    boolean hasComment();
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
     */
    YOUMECommonProtocol.YoumeComm.MsgComment getComment();
  }
  /**
   * Protobuf type {@code YOUMEServiceProtocol.AppTips}
   */
  public  static final class AppTips extends
      com.google.protobuf.GeneratedMessageLite<
          AppTips, AppTips.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.AppTips)
      AppTipsOrBuilder {
    private AppTips() {
      channelId_ = com.google.protobuf.ByteString.EMPTY;
      title_ = com.google.protobuf.ByteString.EMPTY;
      content_ = com.google.protobuf.ByteString.EMPTY;
      linkKeywords_ = com.google.protobuf.ByteString.EMPTY;
      linkAddr_ = com.google.protobuf.ByteString.EMPTY;
      loopWeekday_ = com.google.protobuf.ByteString.EMPTY;
      startDatetime_ = com.google.protobuf.ByteString.EMPTY;
      endDatetime_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int TIPS_ID_FIELD_NUMBER = 1;
    private long tipsId_;
    /**
     * <code>required uint64 tips_id = 1;</code>
     */
    public boolean hasTipsId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 tips_id = 1;</code>
     */
    public long getTipsId() {
      return tipsId_;
    }
    /**
     * <code>required uint64 tips_id = 1;</code>
     */
    private void setTipsId(long value) {
      bitField0_ |= 0x00000001;
      tipsId_ = value;
    }
    /**
     * <code>required uint64 tips_id = 1;</code>
     */
    private void clearTipsId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      tipsId_ = 0L;
    }

    public static final int CHANNEL_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString channelId_;
    /**
     * <code>required bytes channel_id = 2;</code>
     */
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes channel_id = 2;</code>
     */
    public com.google.protobuf.ByteString getChannelId() {
      return channelId_;
    }
    /**
     * <code>required bytes channel_id = 2;</code>
     */
    private void setChannelId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      channelId_ = value;
    }
    /**
     * <code>required bytes channel_id = 2;</code>
     */
    private void clearChannelId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      channelId_ = getDefaultInstance().getChannelId();
    }

    public static final int TITLE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString title_;
    /**
     * <code>required bytes title = 3;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes title = 3;</code>
     */
    public com.google.protobuf.ByteString getTitle() {
      return title_;
    }
    /**
     * <code>required bytes title = 3;</code>
     */
    private void setTitle(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      title_ = value;
    }
    /**
     * <code>required bytes title = 3;</code>
     */
    private void clearTitle() {
      bitField0_ = (bitField0_ & ~0x00000004);
      title_ = getDefaultInstance().getTitle();
    }

    public static final int TIPS_TYPE_FIELD_NUMBER = 4;
    private int tipsType_;
    /**
     * <code>required int32 tips_type = 4;</code>
     */
    public boolean hasTipsType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 tips_type = 4;</code>
     */
    public int getTipsType() {
      return tipsType_;
    }
    /**
     * <code>required int32 tips_type = 4;</code>
     */
    private void setTipsType(int value) {
      bitField0_ |= 0x00000008;
      tipsType_ = value;
    }
    /**
     * <code>required int32 tips_type = 4;</code>
     */
    private void clearTipsType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      tipsType_ = 0;
    }

    public static final int LOOP_TYPE_FIELD_NUMBER = 5;
    private int loopType_;
    /**
     * <code>required int32 loop_type = 5;</code>
     */
    public boolean hasLoopType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 loop_type = 5;</code>
     */
    public int getLoopType() {
      return loopType_;
    }
    /**
     * <code>required int32 loop_type = 5;</code>
     */
    private void setLoopType(int value) {
      bitField0_ |= 0x00000010;
      loopType_ = value;
    }
    /**
     * <code>required int32 loop_type = 5;</code>
     */
    private void clearLoopType() {
      bitField0_ = (bitField0_ & ~0x00000010);
      loopType_ = 0;
    }

    public static final int CONTENT_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>required bytes content = 6;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bytes content = 6;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    /**
     * <code>required bytes content = 6;</code>
     */
    private void setContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      content_ = value;
    }
    /**
     * <code>required bytes content = 6;</code>
     */
    private void clearContent() {
      bitField0_ = (bitField0_ & ~0x00000020);
      content_ = getDefaultInstance().getContent();
    }

    public static final int LINK_KEYWORDS_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString linkKeywords_;
    /**
     * <code>required bytes link_keywords = 7;</code>
     */
    public boolean hasLinkKeywords() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required bytes link_keywords = 7;</code>
     */
    public com.google.protobuf.ByteString getLinkKeywords() {
      return linkKeywords_;
    }
    /**
     * <code>required bytes link_keywords = 7;</code>
     */
    private void setLinkKeywords(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      linkKeywords_ = value;
    }
    /**
     * <code>required bytes link_keywords = 7;</code>
     */
    private void clearLinkKeywords() {
      bitField0_ = (bitField0_ & ~0x00000040);
      linkKeywords_ = getDefaultInstance().getLinkKeywords();
    }

    public static final int LINK_ADDR_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString linkAddr_;
    /**
     * <code>required bytes link_addr = 8;</code>
     */
    public boolean hasLinkAddr() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required bytes link_addr = 8;</code>
     */
    public com.google.protobuf.ByteString getLinkAddr() {
      return linkAddr_;
    }
    /**
     * <code>required bytes link_addr = 8;</code>
     */
    private void setLinkAddr(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      linkAddr_ = value;
    }
    /**
     * <code>required bytes link_addr = 8;</code>
     */
    private void clearLinkAddr() {
      bitField0_ = (bitField0_ & ~0x00000080);
      linkAddr_ = getDefaultInstance().getLinkAddr();
    }

    public static final int LOOP_WEEKDAY_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString loopWeekday_;
    /**
     * <code>required bytes loop_weekday = 9;</code>
     */
    public boolean hasLoopWeekday() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required bytes loop_weekday = 9;</code>
     */
    public com.google.protobuf.ByteString getLoopWeekday() {
      return loopWeekday_;
    }
    /**
     * <code>required bytes loop_weekday = 9;</code>
     */
    private void setLoopWeekday(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      loopWeekday_ = value;
    }
    /**
     * <code>required bytes loop_weekday = 9;</code>
     */
    private void clearLoopWeekday() {
      bitField0_ = (bitField0_ & ~0x00000100);
      loopWeekday_ = getDefaultInstance().getLoopWeekday();
    }

    public static final int START_DATETIME_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString startDatetime_;
    /**
     * <code>required bytes start_datetime = 10;</code>
     */
    public boolean hasStartDatetime() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required bytes start_datetime = 10;</code>
     */
    public com.google.protobuf.ByteString getStartDatetime() {
      return startDatetime_;
    }
    /**
     * <code>required bytes start_datetime = 10;</code>
     */
    private void setStartDatetime(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      startDatetime_ = value;
    }
    /**
     * <code>required bytes start_datetime = 10;</code>
     */
    private void clearStartDatetime() {
      bitField0_ = (bitField0_ & ~0x00000200);
      startDatetime_ = getDefaultInstance().getStartDatetime();
    }

    public static final int END_DATETIME_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString endDatetime_;
    /**
     * <code>required bytes end_datetime = 11;</code>
     */
    public boolean hasEndDatetime() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required bytes end_datetime = 11;</code>
     */
    public com.google.protobuf.ByteString getEndDatetime() {
      return endDatetime_;
    }
    /**
     * <code>required bytes end_datetime = 11;</code>
     */
    private void setEndDatetime(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      endDatetime_ = value;
    }
    /**
     * <code>required bytes end_datetime = 11;</code>
     */
    private void clearEndDatetime() {
      bitField0_ = (bitField0_ & ~0x00000400);
      endDatetime_ = getDefaultInstance().getEndDatetime();
    }

    public static final int ENABLE_FIELD_NUMBER = 12;
    private int enable_;
    /**
     * <code>required uint32 enable = 12;</code>
     */
    public boolean hasEnable() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required uint32 enable = 12;</code>
     */
    public int getEnable() {
      return enable_;
    }
    /**
     * <code>required uint32 enable = 12;</code>
     */
    private void setEnable(int value) {
      bitField0_ |= 0x00000800;
      enable_ = value;
    }
    /**
     * <code>required uint32 enable = 12;</code>
     */
    private void clearEnable() {
      bitField0_ = (bitField0_ & ~0x00000800);
      enable_ = 0;
    }

    public static final int OLD_ID_FIELD_NUMBER = 13;
    private long oldId_;
    /**
     * <code>required uint64 old_id = 13;</code>
     */
    public boolean hasOldId() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required uint64 old_id = 13;</code>
     */
    public long getOldId() {
      return oldId_;
    }
    /**
     * <code>required uint64 old_id = 13;</code>
     */
    private void setOldId(long value) {
      bitField0_ |= 0x00001000;
      oldId_ = value;
    }
    /**
     * <code>required uint64 old_id = 13;</code>
     */
    private void clearOldId() {
      bitField0_ = (bitField0_ & ~0x00001000);
      oldId_ = 0L;
    }

    public static final int COMMENT_FIELD_NUMBER = 14;
    private YOUMECommonProtocol.YoumeComm.MsgComment comment_;
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
     */
    public boolean hasComment() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
     */
    public YOUMECommonProtocol.YoumeComm.MsgComment getComment() {
      return comment_ == null ? YOUMECommonProtocol.YoumeComm.MsgComment.getDefaultInstance() : comment_;
    }
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
     */
    private void setComment(YOUMECommonProtocol.YoumeComm.MsgComment value) {
      if (value == null) {
        throw new NullPointerException();
      }
      comment_ = value;
      bitField0_ |= 0x00002000;
      }
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
     */
    private void setComment(
        YOUMECommonProtocol.YoumeComm.MsgComment.Builder builderForValue) {
      comment_ = builderForValue.build();
      bitField0_ |= 0x00002000;
    }
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
     */
    private void mergeComment(YOUMECommonProtocol.YoumeComm.MsgComment value) {
      if (comment_ != null &&
          comment_ != YOUMECommonProtocol.YoumeComm.MsgComment.getDefaultInstance()) {
        comment_ =
          YOUMECommonProtocol.YoumeComm.MsgComment.newBuilder(comment_).mergeFrom(value).buildPartial();
      } else {
        comment_ = value;
      }
      bitField0_ |= 0x00002000;
    }
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
     */
    private void clearComment() {  comment_ = null;
      bitField0_ = (bitField0_ & ~0x00002000);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, tipsId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, channelId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, title_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, tipsType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, loopType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, content_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, linkKeywords_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, linkAddr_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, loopWeekday_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, startDatetime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, endDatetime_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt32(12, enable_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeUInt64(13, oldId_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeMessage(14, getComment());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, tipsId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, channelId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, title_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, tipsType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, loopType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, content_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, linkKeywords_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, linkAddr_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, loopWeekday_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, startDatetime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, endDatetime_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, enable_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(13, oldId_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, getComment());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeTips.AppTips parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeTips.AppTips parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeTips.AppTips parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeTips.AppTips parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeTips.AppTips parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeTips.AppTips parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeTips.AppTips parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeTips.AppTips parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeTips.AppTips parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeTips.AppTips parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeTips.AppTips prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code YOUMEServiceProtocol.AppTips}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeTips.AppTips, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.AppTips)
        YOUMEServiceProtocol.YoumeTips.AppTipsOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeTips.AppTips.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required uint64 tips_id = 1;</code>
       */
      public boolean hasTipsId() {
        return instance.hasTipsId();
      }
      /**
       * <code>required uint64 tips_id = 1;</code>
       */
      public long getTipsId() {
        return instance.getTipsId();
      }
      /**
       * <code>required uint64 tips_id = 1;</code>
       */
      public Builder setTipsId(long value) {
        copyOnWrite();
        instance.setTipsId(value);
        return this;
      }
      /**
       * <code>required uint64 tips_id = 1;</code>
       */
      public Builder clearTipsId() {
        copyOnWrite();
        instance.clearTipsId();
        return this;
      }

      /**
       * <code>required bytes channel_id = 2;</code>
       */
      public boolean hasChannelId() {
        return instance.hasChannelId();
      }
      /**
       * <code>required bytes channel_id = 2;</code>
       */
      public com.google.protobuf.ByteString getChannelId() {
        return instance.getChannelId();
      }
      /**
       * <code>required bytes channel_id = 2;</code>
       */
      public Builder setChannelId(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setChannelId(value);
        return this;
      }
      /**
       * <code>required bytes channel_id = 2;</code>
       */
      public Builder clearChannelId() {
        copyOnWrite();
        instance.clearChannelId();
        return this;
      }

      /**
       * <code>required bytes title = 3;</code>
       */
      public boolean hasTitle() {
        return instance.hasTitle();
      }
      /**
       * <code>required bytes title = 3;</code>
       */
      public com.google.protobuf.ByteString getTitle() {
        return instance.getTitle();
      }
      /**
       * <code>required bytes title = 3;</code>
       */
      public Builder setTitle(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTitle(value);
        return this;
      }
      /**
       * <code>required bytes title = 3;</code>
       */
      public Builder clearTitle() {
        copyOnWrite();
        instance.clearTitle();
        return this;
      }

      /**
       * <code>required int32 tips_type = 4;</code>
       */
      public boolean hasTipsType() {
        return instance.hasTipsType();
      }
      /**
       * <code>required int32 tips_type = 4;</code>
       */
      public int getTipsType() {
        return instance.getTipsType();
      }
      /**
       * <code>required int32 tips_type = 4;</code>
       */
      public Builder setTipsType(int value) {
        copyOnWrite();
        instance.setTipsType(value);
        return this;
      }
      /**
       * <code>required int32 tips_type = 4;</code>
       */
      public Builder clearTipsType() {
        copyOnWrite();
        instance.clearTipsType();
        return this;
      }

      /**
       * <code>required int32 loop_type = 5;</code>
       */
      public boolean hasLoopType() {
        return instance.hasLoopType();
      }
      /**
       * <code>required int32 loop_type = 5;</code>
       */
      public int getLoopType() {
        return instance.getLoopType();
      }
      /**
       * <code>required int32 loop_type = 5;</code>
       */
      public Builder setLoopType(int value) {
        copyOnWrite();
        instance.setLoopType(value);
        return this;
      }
      /**
       * <code>required int32 loop_type = 5;</code>
       */
      public Builder clearLoopType() {
        copyOnWrite();
        instance.clearLoopType();
        return this;
      }

      /**
       * <code>required bytes content = 6;</code>
       */
      public boolean hasContent() {
        return instance.hasContent();
      }
      /**
       * <code>required bytes content = 6;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return instance.getContent();
      }
      /**
       * <code>required bytes content = 6;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <code>required bytes content = 6;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }

      /**
       * <code>required bytes link_keywords = 7;</code>
       */
      public boolean hasLinkKeywords() {
        return instance.hasLinkKeywords();
      }
      /**
       * <code>required bytes link_keywords = 7;</code>
       */
      public com.google.protobuf.ByteString getLinkKeywords() {
        return instance.getLinkKeywords();
      }
      /**
       * <code>required bytes link_keywords = 7;</code>
       */
      public Builder setLinkKeywords(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLinkKeywords(value);
        return this;
      }
      /**
       * <code>required bytes link_keywords = 7;</code>
       */
      public Builder clearLinkKeywords() {
        copyOnWrite();
        instance.clearLinkKeywords();
        return this;
      }

      /**
       * <code>required bytes link_addr = 8;</code>
       */
      public boolean hasLinkAddr() {
        return instance.hasLinkAddr();
      }
      /**
       * <code>required bytes link_addr = 8;</code>
       */
      public com.google.protobuf.ByteString getLinkAddr() {
        return instance.getLinkAddr();
      }
      /**
       * <code>required bytes link_addr = 8;</code>
       */
      public Builder setLinkAddr(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLinkAddr(value);
        return this;
      }
      /**
       * <code>required bytes link_addr = 8;</code>
       */
      public Builder clearLinkAddr() {
        copyOnWrite();
        instance.clearLinkAddr();
        return this;
      }

      /**
       * <code>required bytes loop_weekday = 9;</code>
       */
      public boolean hasLoopWeekday() {
        return instance.hasLoopWeekday();
      }
      /**
       * <code>required bytes loop_weekday = 9;</code>
       */
      public com.google.protobuf.ByteString getLoopWeekday() {
        return instance.getLoopWeekday();
      }
      /**
       * <code>required bytes loop_weekday = 9;</code>
       */
      public Builder setLoopWeekday(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLoopWeekday(value);
        return this;
      }
      /**
       * <code>required bytes loop_weekday = 9;</code>
       */
      public Builder clearLoopWeekday() {
        copyOnWrite();
        instance.clearLoopWeekday();
        return this;
      }

      /**
       * <code>required bytes start_datetime = 10;</code>
       */
      public boolean hasStartDatetime() {
        return instance.hasStartDatetime();
      }
      /**
       * <code>required bytes start_datetime = 10;</code>
       */
      public com.google.protobuf.ByteString getStartDatetime() {
        return instance.getStartDatetime();
      }
      /**
       * <code>required bytes start_datetime = 10;</code>
       */
      public Builder setStartDatetime(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStartDatetime(value);
        return this;
      }
      /**
       * <code>required bytes start_datetime = 10;</code>
       */
      public Builder clearStartDatetime() {
        copyOnWrite();
        instance.clearStartDatetime();
        return this;
      }

      /**
       * <code>required bytes end_datetime = 11;</code>
       */
      public boolean hasEndDatetime() {
        return instance.hasEndDatetime();
      }
      /**
       * <code>required bytes end_datetime = 11;</code>
       */
      public com.google.protobuf.ByteString getEndDatetime() {
        return instance.getEndDatetime();
      }
      /**
       * <code>required bytes end_datetime = 11;</code>
       */
      public Builder setEndDatetime(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEndDatetime(value);
        return this;
      }
      /**
       * <code>required bytes end_datetime = 11;</code>
       */
      public Builder clearEndDatetime() {
        copyOnWrite();
        instance.clearEndDatetime();
        return this;
      }

      /**
       * <code>required uint32 enable = 12;</code>
       */
      public boolean hasEnable() {
        return instance.hasEnable();
      }
      /**
       * <code>required uint32 enable = 12;</code>
       */
      public int getEnable() {
        return instance.getEnable();
      }
      /**
       * <code>required uint32 enable = 12;</code>
       */
      public Builder setEnable(int value) {
        copyOnWrite();
        instance.setEnable(value);
        return this;
      }
      /**
       * <code>required uint32 enable = 12;</code>
       */
      public Builder clearEnable() {
        copyOnWrite();
        instance.clearEnable();
        return this;
      }

      /**
       * <code>required uint64 old_id = 13;</code>
       */
      public boolean hasOldId() {
        return instance.hasOldId();
      }
      /**
       * <code>required uint64 old_id = 13;</code>
       */
      public long getOldId() {
        return instance.getOldId();
      }
      /**
       * <code>required uint64 old_id = 13;</code>
       */
      public Builder setOldId(long value) {
        copyOnWrite();
        instance.setOldId(value);
        return this;
      }
      /**
       * <code>required uint64 old_id = 13;</code>
       */
      public Builder clearOldId() {
        copyOnWrite();
        instance.clearOldId();
        return this;
      }

      /**
       * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
       */
      public boolean hasComment() {
        return instance.hasComment();
      }
      /**
       * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
       */
      public YOUMECommonProtocol.YoumeComm.MsgComment getComment() {
        return instance.getComment();
      }
      /**
       * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
       */
      public Builder setComment(YOUMECommonProtocol.YoumeComm.MsgComment value) {
        copyOnWrite();
        instance.setComment(value);
        return this;
        }
      /**
       * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
       */
      public Builder setComment(
          YOUMECommonProtocol.YoumeComm.MsgComment.Builder builderForValue) {
        copyOnWrite();
        instance.setComment(builderForValue);
        return this;
      }
      /**
       * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
       */
      public Builder mergeComment(YOUMECommonProtocol.YoumeComm.MsgComment value) {
        copyOnWrite();
        instance.mergeComment(value);
        return this;
      }
      /**
       * <code>optional .YOUMECommonProtocol.MsgComment comment = 14;</code>
       */
      public Builder clearComment() {  copyOnWrite();
        instance.clearComment();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.AppTips)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeTips.AppTips();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasTipsId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasChannelId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasTitle()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasTipsType()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasLoopType()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasContent()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasLinkKeywords()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasLinkAddr()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasLoopWeekday()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasStartDatetime()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasEndDatetime()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasEnable()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasOldId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (hasComment()) {
            if (!getComment().isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeTips.AppTips other = (YOUMEServiceProtocol.YoumeTips.AppTips) arg1;
          tipsId_ = visitor.visitLong(
              hasTipsId(), tipsId_,
              other.hasTipsId(), other.tipsId_);
          channelId_ = visitor.visitByteString(
              hasChannelId(), channelId_,
              other.hasChannelId(), other.channelId_);
          title_ = visitor.visitByteString(
              hasTitle(), title_,
              other.hasTitle(), other.title_);
          tipsType_ = visitor.visitInt(
              hasTipsType(), tipsType_,
              other.hasTipsType(), other.tipsType_);
          loopType_ = visitor.visitInt(
              hasLoopType(), loopType_,
              other.hasLoopType(), other.loopType_);
          content_ = visitor.visitByteString(
              hasContent(), content_,
              other.hasContent(), other.content_);
          linkKeywords_ = visitor.visitByteString(
              hasLinkKeywords(), linkKeywords_,
              other.hasLinkKeywords(), other.linkKeywords_);
          linkAddr_ = visitor.visitByteString(
              hasLinkAddr(), linkAddr_,
              other.hasLinkAddr(), other.linkAddr_);
          loopWeekday_ = visitor.visitByteString(
              hasLoopWeekday(), loopWeekday_,
              other.hasLoopWeekday(), other.loopWeekday_);
          startDatetime_ = visitor.visitByteString(
              hasStartDatetime(), startDatetime_,
              other.hasStartDatetime(), other.startDatetime_);
          endDatetime_ = visitor.visitByteString(
              hasEndDatetime(), endDatetime_,
              other.hasEndDatetime(), other.endDatetime_);
          enable_ = visitor.visitInt(
              hasEnable(), enable_,
              other.hasEnable(), other.enable_);
          oldId_ = visitor.visitLong(
              hasOldId(), oldId_,
              other.hasOldId(), other.oldId_);
          comment_ = visitor.visitMessage(comment_, other.comment_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  tipsId_ = input.readUInt64();
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000002;
                  channelId_ = input.readBytes();
                  break;
                }
                case 26: {
                  bitField0_ |= 0x00000004;
                  title_ = input.readBytes();
                  break;
                }
                case 32: {
                  bitField0_ |= 0x00000008;
                  tipsType_ = input.readInt32();
                  break;
                }
                case 40: {
                  bitField0_ |= 0x00000010;
                  loopType_ = input.readInt32();
                  break;
                }
                case 50: {
                  bitField0_ |= 0x00000020;
                  content_ = input.readBytes();
                  break;
                }
                case 58: {
                  bitField0_ |= 0x00000040;
                  linkKeywords_ = input.readBytes();
                  break;
                }
                case 66: {
                  bitField0_ |= 0x00000080;
                  linkAddr_ = input.readBytes();
                  break;
                }
                case 74: {
                  bitField0_ |= 0x00000100;
                  loopWeekday_ = input.readBytes();
                  break;
                }
                case 82: {
                  bitField0_ |= 0x00000200;
                  startDatetime_ = input.readBytes();
                  break;
                }
                case 90: {
                  bitField0_ |= 0x00000400;
                  endDatetime_ = input.readBytes();
                  break;
                }
                case 96: {
                  bitField0_ |= 0x00000800;
                  enable_ = input.readUInt32();
                  break;
                }
                case 104: {
                  bitField0_ |= 0x00001000;
                  oldId_ = input.readUInt64();
                  break;
                }
                case 114: {
                  YOUMECommonProtocol.YoumeComm.MsgComment.Builder subBuilder = null;
                  if (((bitField0_ & 0x00002000) == 0x00002000)) {
                    subBuilder = comment_.toBuilder();
                  }
                  comment_ = input.readMessage(YOUMECommonProtocol.YoumeComm.MsgComment.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(comment_);
                    comment_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00002000;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeTips.AppTips.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.AppTips)
    private static final YOUMEServiceProtocol.YoumeTips.AppTips DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AppTips();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeTips.AppTips getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AppTips> PARSER;

    public static com.google.protobuf.Parser<AppTips> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GetTipsRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.GetTipsRsp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    boolean hasRet();
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    int getRet();

    /**
     * <code>required int32 tips_cnt = 3;</code>
     */
    boolean hasTipsCnt();
    /**
     * <code>required int32 tips_cnt = 3;</code>
     */
    int getTipsCnt();

    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    java.util.List<YOUMEServiceProtocol.YoumeTips.AppTips> 
        getTipsListList();
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    YOUMEServiceProtocol.YoumeTips.AppTips getTipsList(int index);
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    int getTipsListCount();
  }
  /**
   * Protobuf type {@code YOUMEServiceProtocol.GetTipsRsp}
   */
  public  static final class GetTipsRsp extends
      com.google.protobuf.GeneratedMessageLite<
          GetTipsRsp, GetTipsRsp.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.GetTipsRsp)
      GetTipsRspOrBuilder {
    private GetTipsRsp() {
      tipsList_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
    }

    public static final int RET_FIELD_NUMBER = 2;
    private int ret_;
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    public int getRet() {
      return ret_;
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    private void setRet(int value) {
      bitField0_ |= 0x00000002;
      ret_ = value;
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    private void clearRet() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ret_ = 0;
    }

    public static final int TIPS_CNT_FIELD_NUMBER = 3;
    private int tipsCnt_;
    /**
     * <code>required int32 tips_cnt = 3;</code>
     */
    public boolean hasTipsCnt() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 tips_cnt = 3;</code>
     */
    public int getTipsCnt() {
      return tipsCnt_;
    }
    /**
     * <code>required int32 tips_cnt = 3;</code>
     */
    private void setTipsCnt(int value) {
      bitField0_ |= 0x00000004;
      tipsCnt_ = value;
    }
    /**
     * <code>required int32 tips_cnt = 3;</code>
     */
    private void clearTipsCnt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tipsCnt_ = 0;
    }

    public static final int TIPS_LIST_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<YOUMEServiceProtocol.YoumeTips.AppTips> tipsList_;
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    public java.util.List<YOUMEServiceProtocol.YoumeTips.AppTips> getTipsListList() {
      return tipsList_;
    }
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    public java.util.List<? extends YOUMEServiceProtocol.YoumeTips.AppTipsOrBuilder> 
        getTipsListOrBuilderList() {
      return tipsList_;
    }
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    public int getTipsListCount() {
      return tipsList_.size();
    }
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    public YOUMEServiceProtocol.YoumeTips.AppTips getTipsList(int index) {
      return tipsList_.get(index);
    }
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    public YOUMEServiceProtocol.YoumeTips.AppTipsOrBuilder getTipsListOrBuilder(
        int index) {
      return tipsList_.get(index);
    }
    private void ensureTipsListIsMutable() {
      if (!tipsList_.isModifiable()) {
        tipsList_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tipsList_);
       }
    }

    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    private void setTipsList(
        int index, YOUMEServiceProtocol.YoumeTips.AppTips value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureTipsListIsMutable();
      tipsList_.set(index, value);
    }
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    private void setTipsList(
        int index, YOUMEServiceProtocol.YoumeTips.AppTips.Builder builderForValue) {
      ensureTipsListIsMutable();
      tipsList_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    private void addTipsList(YOUMEServiceProtocol.YoumeTips.AppTips value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureTipsListIsMutable();
      tipsList_.add(value);
    }
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    private void addTipsList(
        int index, YOUMEServiceProtocol.YoumeTips.AppTips value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureTipsListIsMutable();
      tipsList_.add(index, value);
    }
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    private void addTipsList(
        YOUMEServiceProtocol.YoumeTips.AppTips.Builder builderForValue) {
      ensureTipsListIsMutable();
      tipsList_.add(builderForValue.build());
    }
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    private void addTipsList(
        int index, YOUMEServiceProtocol.YoumeTips.AppTips.Builder builderForValue) {
      ensureTipsListIsMutable();
      tipsList_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    private void addAllTipsList(
        java.lang.Iterable<? extends YOUMEServiceProtocol.YoumeTips.AppTips> values) {
      ensureTipsListIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, tipsList_);
    }
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    private void clearTipsList() {
      tipsList_ = emptyProtobufList();
    }
    /**
     * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
     */
    private void removeTipsList(int index) {
      ensureTipsListIsMutable();
      tipsList_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ret_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, tipsCnt_);
      }
      for (int i = 0; i < tipsList_.size(); i++) {
        output.writeMessage(4, tipsList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ret_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, tipsCnt_);
      }
      for (int i = 0; i < tipsList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, tipsList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeTips.GetTipsRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeTips.GetTipsRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeTips.GetTipsRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeTips.GetTipsRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeTips.GetTipsRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeTips.GetTipsRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeTips.GetTipsRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeTips.GetTipsRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeTips.GetTipsRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeTips.GetTipsRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeTips.GetTipsRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code YOUMEServiceProtocol.GetTipsRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeTips.GetTipsRsp, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.GetTipsRsp)
        YOUMEServiceProtocol.YoumeTips.GetTipsRspOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeTips.GetTipsRsp.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public boolean hasRet() {
        return instance.hasRet();
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public int getRet() {
        return instance.getRet();
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public Builder setRet(int value) {
        copyOnWrite();
        instance.setRet(value);
        return this;
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public Builder clearRet() {
        copyOnWrite();
        instance.clearRet();
        return this;
      }

      /**
       * <code>required int32 tips_cnt = 3;</code>
       */
      public boolean hasTipsCnt() {
        return instance.hasTipsCnt();
      }
      /**
       * <code>required int32 tips_cnt = 3;</code>
       */
      public int getTipsCnt() {
        return instance.getTipsCnt();
      }
      /**
       * <code>required int32 tips_cnt = 3;</code>
       */
      public Builder setTipsCnt(int value) {
        copyOnWrite();
        instance.setTipsCnt(value);
        return this;
      }
      /**
       * <code>required int32 tips_cnt = 3;</code>
       */
      public Builder clearTipsCnt() {
        copyOnWrite();
        instance.clearTipsCnt();
        return this;
      }

      /**
       * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
       */
      public java.util.List<YOUMEServiceProtocol.YoumeTips.AppTips> getTipsListList() {
        return java.util.Collections.unmodifiableList(
            instance.getTipsListList());
      }
      /**
       * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
       */
      public int getTipsListCount() {
        return instance.getTipsListCount();
      }/**
       * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
       */
      public YOUMEServiceProtocol.YoumeTips.AppTips getTipsList(int index) {
        return instance.getTipsList(index);
      }
      /**
       * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
       */
      public Builder setTipsList(
          int index, YOUMEServiceProtocol.YoumeTips.AppTips value) {
        copyOnWrite();
        instance.setTipsList(index, value);
        return this;
      }
      /**
       * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
       */
      public Builder setTipsList(
          int index, YOUMEServiceProtocol.YoumeTips.AppTips.Builder builderForValue) {
        copyOnWrite();
        instance.setTipsList(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
       */
      public Builder addTipsList(YOUMEServiceProtocol.YoumeTips.AppTips value) {
        copyOnWrite();
        instance.addTipsList(value);
        return this;
      }
      /**
       * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
       */
      public Builder addTipsList(
          int index, YOUMEServiceProtocol.YoumeTips.AppTips value) {
        copyOnWrite();
        instance.addTipsList(index, value);
        return this;
      }
      /**
       * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
       */
      public Builder addTipsList(
          YOUMEServiceProtocol.YoumeTips.AppTips.Builder builderForValue) {
        copyOnWrite();
        instance.addTipsList(builderForValue);
        return this;
      }
      /**
       * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
       */
      public Builder addTipsList(
          int index, YOUMEServiceProtocol.YoumeTips.AppTips.Builder builderForValue) {
        copyOnWrite();
        instance.addTipsList(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
       */
      public Builder addAllTipsList(
          java.lang.Iterable<? extends YOUMEServiceProtocol.YoumeTips.AppTips> values) {
        copyOnWrite();
        instance.addAllTipsList(values);
        return this;
      }
      /**
       * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
       */
      public Builder clearTipsList() {
        copyOnWrite();
        instance.clearTipsList();
        return this;
      }
      /**
       * <code>repeated .YOUMEServiceProtocol.AppTips tips_list = 4;</code>
       */
      public Builder removeTipsList(int index) {
        copyOnWrite();
        instance.removeTipsList(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.GetTipsRsp)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeTips.GetTipsRsp();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasVersion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasRet()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasTipsCnt()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          for (int i = 0; i < getTipsListCount(); i++) {
            if (!getTipsList(i).isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          tipsList_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeTips.GetTipsRsp other = (YOUMEServiceProtocol.YoumeTips.GetTipsRsp) arg1;
          version_ = visitor.visitInt(
              hasVersion(), version_,
              other.hasVersion(), other.version_);
          ret_ = visitor.visitInt(
              hasRet(), ret_,
              other.hasRet(), other.ret_);
          tipsCnt_ = visitor.visitInt(
              hasTipsCnt(), tipsCnt_,
              other.hasTipsCnt(), other.tipsCnt_);
          tipsList_= visitor.visitList(tipsList_, other.tipsList_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  version_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  ret_ = input.readInt32();
                  break;
                }
                case 24: {
                  bitField0_ |= 0x00000004;
                  tipsCnt_ = input.readInt32();
                  break;
                }
                case 34: {
                  if (!tipsList_.isModifiable()) {
                    tipsList_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(tipsList_);
                  }
                  tipsList_.add(
                      input.readMessage(YOUMEServiceProtocol.YoumeTips.AppTips.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeTips.GetTipsRsp.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetTipsRsp)
    private static final YOUMEServiceProtocol.YoumeTips.GetTipsRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetTipsRsp();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeTips.GetTipsRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GetTipsRsp> PARSER;

    public static com.google.protobuf.Parser<GetTipsRsp> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
