// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notify_svr/youme_notify.proto

package YOUMEServiceProtocol;

public final class YoumeNotify {
  private YoumeNotify() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NotifyRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.NotifyRsp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>required string msg = 2;</code>
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>required string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    java.util.List<YOUMECommonProtocol.YoumeComm.NameValue> 
        getArgsList();
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    YOUMECommonProtocol.YoumeComm.NameValue getArgs(int index);
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    int getArgsCount();
  }
  /**
   * <pre>
   * 通知或命令下发包体, 包体由会话 key 加密
   * </pre>
   *
   * Protobuf type {@code YOUMEServiceProtocol.NotifyRsp}
   */
  public  static final class NotifyRsp extends
      com.google.protobuf.GeneratedMessageLite<
          NotifyRsp, NotifyRsp.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.NotifyRsp)
      NotifyRspOrBuilder {
    private NotifyRsp() {
      msg_ = "";
      args_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private java.lang.String msg_;
    /**
     * <code>required string msg = 2;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      return msg_;
    }
    /**
     * <code>required string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(msg_);
    }
    /**
     * <code>required string msg = 2;</code>
     */
    private void setMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      msg_ = value;
    }
    /**
     * <code>required string msg = 2;</code>
     */
    private void clearMsg() {
      bitField0_ = (bitField0_ & ~0x00000002);
      msg_ = getDefaultInstance().getMsg();
    }
    /**
     * <code>required string msg = 2;</code>
     */
    private void setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      msg_ = value.toStringUtf8();
    }

    public static final int ARGS_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<YOUMECommonProtocol.YoumeComm.NameValue> args_;
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    public java.util.List<YOUMECommonProtocol.YoumeComm.NameValue> getArgsList() {
      return args_;
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    public java.util.List<? extends YOUMECommonProtocol.YoumeComm.NameValueOrBuilder> 
        getArgsOrBuilderList() {
      return args_;
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    public int getArgsCount() {
      return args_.size();
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    public YOUMECommonProtocol.YoumeComm.NameValue getArgs(int index) {
      return args_.get(index);
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    public YOUMECommonProtocol.YoumeComm.NameValueOrBuilder getArgsOrBuilder(
        int index) {
      return args_.get(index);
    }
    private void ensureArgsIsMutable() {
      if (!args_.isModifiable()) {
        args_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(args_);
       }
    }

    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    private void setArgs(
        int index, YOUMECommonProtocol.YoumeComm.NameValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureArgsIsMutable();
      args_.set(index, value);
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    private void setArgs(
        int index, YOUMECommonProtocol.YoumeComm.NameValue.Builder builderForValue) {
      ensureArgsIsMutable();
      args_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    private void addArgs(YOUMECommonProtocol.YoumeComm.NameValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureArgsIsMutable();
      args_.add(value);
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    private void addArgs(
        int index, YOUMECommonProtocol.YoumeComm.NameValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureArgsIsMutable();
      args_.add(index, value);
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    private void addArgs(
        YOUMECommonProtocol.YoumeComm.NameValue.Builder builderForValue) {
      ensureArgsIsMutable();
      args_.add(builderForValue.build());
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    private void addArgs(
        int index, YOUMECommonProtocol.YoumeComm.NameValue.Builder builderForValue) {
      ensureArgsIsMutable();
      args_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    private void addAllArgs(
        java.lang.Iterable<? extends YOUMECommonProtocol.YoumeComm.NameValue> values) {
      ensureArgsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, args_);
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    private void clearArgs() {
      args_ = emptyProtobufList();
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
     */
    private void removeArgs(int index) {
      ensureArgsIsMutable();
      args_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getMsg());
      }
      for (int i = 0; i < args_.size(); i++) {
        output.writeMessage(3, args_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getMsg());
      }
      for (int i = 0; i < args_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, args_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeNotify.NotifyRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeNotify.NotifyRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 通知或命令下发包体, 包体由会话 key 加密
     * </pre>
     *
     * Protobuf type {@code YOUMEServiceProtocol.NotifyRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeNotify.NotifyRsp, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.NotifyRsp)
        YOUMEServiceProtocol.YoumeNotify.NotifyRspOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeNotify.NotifyRsp.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       * <code>required string msg = 2;</code>
       */
      public boolean hasMsg() {
        return instance.hasMsg();
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        return instance.getMsg();
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        return instance.getMsgBytes();
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        copyOnWrite();
        instance.setMsg(value);
        return this;
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }
      /**
       * <code>required string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMsgBytes(value);
        return this;
      }

      /**
       * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
       */
      public java.util.List<YOUMECommonProtocol.YoumeComm.NameValue> getArgsList() {
        return java.util.Collections.unmodifiableList(
            instance.getArgsList());
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
       */
      public int getArgsCount() {
        return instance.getArgsCount();
      }/**
       * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
       */
      public YOUMECommonProtocol.YoumeComm.NameValue getArgs(int index) {
        return instance.getArgs(index);
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
       */
      public Builder setArgs(
          int index, YOUMECommonProtocol.YoumeComm.NameValue value) {
        copyOnWrite();
        instance.setArgs(index, value);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
       */
      public Builder setArgs(
          int index, YOUMECommonProtocol.YoumeComm.NameValue.Builder builderForValue) {
        copyOnWrite();
        instance.setArgs(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
       */
      public Builder addArgs(YOUMECommonProtocol.YoumeComm.NameValue value) {
        copyOnWrite();
        instance.addArgs(value);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
       */
      public Builder addArgs(
          int index, YOUMECommonProtocol.YoumeComm.NameValue value) {
        copyOnWrite();
        instance.addArgs(index, value);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
       */
      public Builder addArgs(
          YOUMECommonProtocol.YoumeComm.NameValue.Builder builderForValue) {
        copyOnWrite();
        instance.addArgs(builderForValue);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
       */
      public Builder addArgs(
          int index, YOUMECommonProtocol.YoumeComm.NameValue.Builder builderForValue) {
        copyOnWrite();
        instance.addArgs(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
       */
      public Builder addAllArgs(
          java.lang.Iterable<? extends YOUMECommonProtocol.YoumeComm.NameValue> values) {
        copyOnWrite();
        instance.addAllArgs(values);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
       */
      public Builder clearArgs() {
        copyOnWrite();
        instance.clearArgs();
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue args = 3;</code>
       */
      public Builder removeArgs(int index) {
        copyOnWrite();
        instance.removeArgs(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.NotifyRsp)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeNotify.NotifyRsp();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasVersion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasMsg()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          for (int i = 0; i < getArgsCount(); i++) {
            if (!getArgs(i).isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          args_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeNotify.NotifyRsp other = (YOUMEServiceProtocol.YoumeNotify.NotifyRsp) arg1;
          version_ = visitor.visitInt(
              hasVersion(), version_,
              other.hasVersion(), other.version_);
          msg_ = visitor.visitString(
              hasMsg(), msg_,
              other.hasMsg(), other.msg_);
          args_= visitor.visitList(args_, other.args_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  version_ = input.readInt32();
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  msg_ = s;
                  break;
                }
                case 26: {
                  if (!args_.isModifiable()) {
                    args_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(args_);
                  }
                  args_.add(
                      input.readMessage(YOUMECommonProtocol.YoumeComm.NameValue.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeNotify.NotifyRsp.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.NotifyRsp)
    private static final YOUMEServiceProtocol.YoumeNotify.NotifyRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NotifyRsp();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeNotify.NotifyRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NotifyRsp> PARSER;

    public static com.google.protobuf.Parser<NotifyRsp> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NotifyReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.NotifyReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>required int32 notify_type = 2;</code>
     */
    boolean hasNotifyType();
    /**
     * <code>required int32 notify_type = 2;</code>
     */
    int getNotifyType();

    /**
     * <code>required bytes snder_id = 3;</code>
     */
    boolean hasSnderId();
    /**
     * <code>required bytes snder_id = 3;</code>
     */
    com.google.protobuf.ByteString getSnderId();

    /**
     * <code>required bytes recver_id = 4;</code>
     */
    boolean hasRecverId();
    /**
     * <code>required bytes recver_id = 4;</code>
     */
    com.google.protobuf.ByteString getRecverId();

    /**
     * <code>required int32 notify_property = 5;</code>
     */
    boolean hasNotifyProperty();
    /**
     * <code>required int32 notify_property = 5;</code>
     */
    int getNotifyProperty();

    /**
     * <code>optional bytes notify_msg = 6;</code>
     */
    boolean hasNotifyMsg();
    /**
     * <code>optional bytes notify_msg = 6;</code>
     */
    com.google.protobuf.ByteString getNotifyMsg();

    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    java.util.List<YOUMECommonProtocol.YoumeComm.NameValue> 
        getNotifyArgsList();
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    YOUMECommonProtocol.YoumeComm.NameValue getNotifyArgs(int index);
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    int getNotifyArgsCount();
  }
  /**
   * <pre>
   * 通知请求包体
   * </pre>
   *
   * Protobuf type {@code YOUMEServiceProtocol.NotifyReq}
   */
  public  static final class NotifyReq extends
      com.google.protobuf.GeneratedMessageLite<
          NotifyReq, NotifyReq.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.NotifyReq)
      NotifyReqOrBuilder {
    private NotifyReq() {
      snderId_ = com.google.protobuf.ByteString.EMPTY;
      recverId_ = com.google.protobuf.ByteString.EMPTY;
      notifyMsg_ = com.google.protobuf.ByteString.EMPTY;
      notifyArgs_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
    }

    public static final int NOTIFY_TYPE_FIELD_NUMBER = 2;
    private int notifyType_;
    /**
     * <code>required int32 notify_type = 2;</code>
     */
    public boolean hasNotifyType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 notify_type = 2;</code>
     */
    public int getNotifyType() {
      return notifyType_;
    }
    /**
     * <code>required int32 notify_type = 2;</code>
     */
    private void setNotifyType(int value) {
      bitField0_ |= 0x00000002;
      notifyType_ = value;
    }
    /**
     * <code>required int32 notify_type = 2;</code>
     */
    private void clearNotifyType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      notifyType_ = 0;
    }

    public static final int SNDER_ID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString snderId_;
    /**
     * <code>required bytes snder_id = 3;</code>
     */
    public boolean hasSnderId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes snder_id = 3;</code>
     */
    public com.google.protobuf.ByteString getSnderId() {
      return snderId_;
    }
    /**
     * <code>required bytes snder_id = 3;</code>
     */
    private void setSnderId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      snderId_ = value;
    }
    /**
     * <code>required bytes snder_id = 3;</code>
     */
    private void clearSnderId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      snderId_ = getDefaultInstance().getSnderId();
    }

    public static final int RECVER_ID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString recverId_;
    /**
     * <code>required bytes recver_id = 4;</code>
     */
    public boolean hasRecverId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes recver_id = 4;</code>
     */
    public com.google.protobuf.ByteString getRecverId() {
      return recverId_;
    }
    /**
     * <code>required bytes recver_id = 4;</code>
     */
    private void setRecverId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      recverId_ = value;
    }
    /**
     * <code>required bytes recver_id = 4;</code>
     */
    private void clearRecverId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      recverId_ = getDefaultInstance().getRecverId();
    }

    public static final int NOTIFY_PROPERTY_FIELD_NUMBER = 5;
    private int notifyProperty_;
    /**
     * <code>required int32 notify_property = 5;</code>
     */
    public boolean hasNotifyProperty() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 notify_property = 5;</code>
     */
    public int getNotifyProperty() {
      return notifyProperty_;
    }
    /**
     * <code>required int32 notify_property = 5;</code>
     */
    private void setNotifyProperty(int value) {
      bitField0_ |= 0x00000010;
      notifyProperty_ = value;
    }
    /**
     * <code>required int32 notify_property = 5;</code>
     */
    private void clearNotifyProperty() {
      bitField0_ = (bitField0_ & ~0x00000010);
      notifyProperty_ = 0;
    }

    public static final int NOTIFY_MSG_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString notifyMsg_;
    /**
     * <code>optional bytes notify_msg = 6;</code>
     */
    public boolean hasNotifyMsg() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes notify_msg = 6;</code>
     */
    public com.google.protobuf.ByteString getNotifyMsg() {
      return notifyMsg_;
    }
    /**
     * <code>optional bytes notify_msg = 6;</code>
     */
    private void setNotifyMsg(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      notifyMsg_ = value;
    }
    /**
     * <code>optional bytes notify_msg = 6;</code>
     */
    private void clearNotifyMsg() {
      bitField0_ = (bitField0_ & ~0x00000020);
      notifyMsg_ = getDefaultInstance().getNotifyMsg();
    }

    public static final int NOTIFY_ARGS_FIELD_NUMBER = 7;
    private com.google.protobuf.Internal.ProtobufList<YOUMECommonProtocol.YoumeComm.NameValue> notifyArgs_;
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    public java.util.List<YOUMECommonProtocol.YoumeComm.NameValue> getNotifyArgsList() {
      return notifyArgs_;
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    public java.util.List<? extends YOUMECommonProtocol.YoumeComm.NameValueOrBuilder> 
        getNotifyArgsOrBuilderList() {
      return notifyArgs_;
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    public int getNotifyArgsCount() {
      return notifyArgs_.size();
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    public YOUMECommonProtocol.YoumeComm.NameValue getNotifyArgs(int index) {
      return notifyArgs_.get(index);
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    public YOUMECommonProtocol.YoumeComm.NameValueOrBuilder getNotifyArgsOrBuilder(
        int index) {
      return notifyArgs_.get(index);
    }
    private void ensureNotifyArgsIsMutable() {
      if (!notifyArgs_.isModifiable()) {
        notifyArgs_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(notifyArgs_);
       }
    }

    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    private void setNotifyArgs(
        int index, YOUMECommonProtocol.YoumeComm.NameValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNotifyArgsIsMutable();
      notifyArgs_.set(index, value);
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    private void setNotifyArgs(
        int index, YOUMECommonProtocol.YoumeComm.NameValue.Builder builderForValue) {
      ensureNotifyArgsIsMutable();
      notifyArgs_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    private void addNotifyArgs(YOUMECommonProtocol.YoumeComm.NameValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNotifyArgsIsMutable();
      notifyArgs_.add(value);
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    private void addNotifyArgs(
        int index, YOUMECommonProtocol.YoumeComm.NameValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNotifyArgsIsMutable();
      notifyArgs_.add(index, value);
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    private void addNotifyArgs(
        YOUMECommonProtocol.YoumeComm.NameValue.Builder builderForValue) {
      ensureNotifyArgsIsMutable();
      notifyArgs_.add(builderForValue.build());
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    private void addNotifyArgs(
        int index, YOUMECommonProtocol.YoumeComm.NameValue.Builder builderForValue) {
      ensureNotifyArgsIsMutable();
      notifyArgs_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    private void addAllNotifyArgs(
        java.lang.Iterable<? extends YOUMECommonProtocol.YoumeComm.NameValue> values) {
      ensureNotifyArgsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, notifyArgs_);
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    private void clearNotifyArgs() {
      notifyArgs_ = emptyProtobufList();
    }
    /**
     * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
     */
    private void removeNotifyArgs(int index) {
      ensureNotifyArgsIsMutable();
      notifyArgs_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, notifyType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, snderId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, recverId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, notifyProperty_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, notifyMsg_);
      }
      for (int i = 0; i < notifyArgs_.size(); i++) {
        output.writeMessage(7, notifyArgs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, notifyType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, snderId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, recverId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, notifyProperty_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, notifyMsg_);
      }
      for (int i = 0; i < notifyArgs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, notifyArgs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeNotify.NotifyReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeNotify.NotifyReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeNotify.NotifyReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 通知请求包体
     * </pre>
     *
     * Protobuf type {@code YOUMEServiceProtocol.NotifyReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeNotify.NotifyReq, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.NotifyReq)
        YOUMEServiceProtocol.YoumeNotify.NotifyReqOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeNotify.NotifyReq.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       * <code>required int32 notify_type = 2;</code>
       */
      public boolean hasNotifyType() {
        return instance.hasNotifyType();
      }
      /**
       * <code>required int32 notify_type = 2;</code>
       */
      public int getNotifyType() {
        return instance.getNotifyType();
      }
      /**
       * <code>required int32 notify_type = 2;</code>
       */
      public Builder setNotifyType(int value) {
        copyOnWrite();
        instance.setNotifyType(value);
        return this;
      }
      /**
       * <code>required int32 notify_type = 2;</code>
       */
      public Builder clearNotifyType() {
        copyOnWrite();
        instance.clearNotifyType();
        return this;
      }

      /**
       * <code>required bytes snder_id = 3;</code>
       */
      public boolean hasSnderId() {
        return instance.hasSnderId();
      }
      /**
       * <code>required bytes snder_id = 3;</code>
       */
      public com.google.protobuf.ByteString getSnderId() {
        return instance.getSnderId();
      }
      /**
       * <code>required bytes snder_id = 3;</code>
       */
      public Builder setSnderId(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSnderId(value);
        return this;
      }
      /**
       * <code>required bytes snder_id = 3;</code>
       */
      public Builder clearSnderId() {
        copyOnWrite();
        instance.clearSnderId();
        return this;
      }

      /**
       * <code>required bytes recver_id = 4;</code>
       */
      public boolean hasRecverId() {
        return instance.hasRecverId();
      }
      /**
       * <code>required bytes recver_id = 4;</code>
       */
      public com.google.protobuf.ByteString getRecverId() {
        return instance.getRecverId();
      }
      /**
       * <code>required bytes recver_id = 4;</code>
       */
      public Builder setRecverId(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRecverId(value);
        return this;
      }
      /**
       * <code>required bytes recver_id = 4;</code>
       */
      public Builder clearRecverId() {
        copyOnWrite();
        instance.clearRecverId();
        return this;
      }

      /**
       * <code>required int32 notify_property = 5;</code>
       */
      public boolean hasNotifyProperty() {
        return instance.hasNotifyProperty();
      }
      /**
       * <code>required int32 notify_property = 5;</code>
       */
      public int getNotifyProperty() {
        return instance.getNotifyProperty();
      }
      /**
       * <code>required int32 notify_property = 5;</code>
       */
      public Builder setNotifyProperty(int value) {
        copyOnWrite();
        instance.setNotifyProperty(value);
        return this;
      }
      /**
       * <code>required int32 notify_property = 5;</code>
       */
      public Builder clearNotifyProperty() {
        copyOnWrite();
        instance.clearNotifyProperty();
        return this;
      }

      /**
       * <code>optional bytes notify_msg = 6;</code>
       */
      public boolean hasNotifyMsg() {
        return instance.hasNotifyMsg();
      }
      /**
       * <code>optional bytes notify_msg = 6;</code>
       */
      public com.google.protobuf.ByteString getNotifyMsg() {
        return instance.getNotifyMsg();
      }
      /**
       * <code>optional bytes notify_msg = 6;</code>
       */
      public Builder setNotifyMsg(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNotifyMsg(value);
        return this;
      }
      /**
       * <code>optional bytes notify_msg = 6;</code>
       */
      public Builder clearNotifyMsg() {
        copyOnWrite();
        instance.clearNotifyMsg();
        return this;
      }

      /**
       * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
       */
      public java.util.List<YOUMECommonProtocol.YoumeComm.NameValue> getNotifyArgsList() {
        return java.util.Collections.unmodifiableList(
            instance.getNotifyArgsList());
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
       */
      public int getNotifyArgsCount() {
        return instance.getNotifyArgsCount();
      }/**
       * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
       */
      public YOUMECommonProtocol.YoumeComm.NameValue getNotifyArgs(int index) {
        return instance.getNotifyArgs(index);
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
       */
      public Builder setNotifyArgs(
          int index, YOUMECommonProtocol.YoumeComm.NameValue value) {
        copyOnWrite();
        instance.setNotifyArgs(index, value);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
       */
      public Builder setNotifyArgs(
          int index, YOUMECommonProtocol.YoumeComm.NameValue.Builder builderForValue) {
        copyOnWrite();
        instance.setNotifyArgs(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
       */
      public Builder addNotifyArgs(YOUMECommonProtocol.YoumeComm.NameValue value) {
        copyOnWrite();
        instance.addNotifyArgs(value);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
       */
      public Builder addNotifyArgs(
          int index, YOUMECommonProtocol.YoumeComm.NameValue value) {
        copyOnWrite();
        instance.addNotifyArgs(index, value);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
       */
      public Builder addNotifyArgs(
          YOUMECommonProtocol.YoumeComm.NameValue.Builder builderForValue) {
        copyOnWrite();
        instance.addNotifyArgs(builderForValue);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
       */
      public Builder addNotifyArgs(
          int index, YOUMECommonProtocol.YoumeComm.NameValue.Builder builderForValue) {
        copyOnWrite();
        instance.addNotifyArgs(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
       */
      public Builder addAllNotifyArgs(
          java.lang.Iterable<? extends YOUMECommonProtocol.YoumeComm.NameValue> values) {
        copyOnWrite();
        instance.addAllNotifyArgs(values);
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
       */
      public Builder clearNotifyArgs() {
        copyOnWrite();
        instance.clearNotifyArgs();
        return this;
      }
      /**
       * <code>repeated .YOUMECommonProtocol.NameValue notify_args = 7;</code>
       */
      public Builder removeNotifyArgs(int index) {
        copyOnWrite();
        instance.removeNotifyArgs(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.NotifyReq)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeNotify.NotifyReq();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasVersion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasNotifyType()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasSnderId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasRecverId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasNotifyProperty()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          for (int i = 0; i < getNotifyArgsCount(); i++) {
            if (!getNotifyArgs(i).isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          notifyArgs_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeNotify.NotifyReq other = (YOUMEServiceProtocol.YoumeNotify.NotifyReq) arg1;
          version_ = visitor.visitInt(
              hasVersion(), version_,
              other.hasVersion(), other.version_);
          notifyType_ = visitor.visitInt(
              hasNotifyType(), notifyType_,
              other.hasNotifyType(), other.notifyType_);
          snderId_ = visitor.visitByteString(
              hasSnderId(), snderId_,
              other.hasSnderId(), other.snderId_);
          recverId_ = visitor.visitByteString(
              hasRecverId(), recverId_,
              other.hasRecverId(), other.recverId_);
          notifyProperty_ = visitor.visitInt(
              hasNotifyProperty(), notifyProperty_,
              other.hasNotifyProperty(), other.notifyProperty_);
          notifyMsg_ = visitor.visitByteString(
              hasNotifyMsg(), notifyMsg_,
              other.hasNotifyMsg(), other.notifyMsg_);
          notifyArgs_= visitor.visitList(notifyArgs_, other.notifyArgs_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  version_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  notifyType_ = input.readInt32();
                  break;
                }
                case 26: {
                  bitField0_ |= 0x00000004;
                  snderId_ = input.readBytes();
                  break;
                }
                case 34: {
                  bitField0_ |= 0x00000008;
                  recverId_ = input.readBytes();
                  break;
                }
                case 40: {
                  bitField0_ |= 0x00000010;
                  notifyProperty_ = input.readInt32();
                  break;
                }
                case 50: {
                  bitField0_ |= 0x00000020;
                  notifyMsg_ = input.readBytes();
                  break;
                }
                case 58: {
                  if (!notifyArgs_.isModifiable()) {
                    notifyArgs_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(notifyArgs_);
                  }
                  notifyArgs_.add(
                      input.readMessage(YOUMECommonProtocol.YoumeComm.NameValue.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeNotify.NotifyReq.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.NotifyReq)
    private static final YOUMEServiceProtocol.YoumeNotify.NotifyReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NotifyReq();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeNotify.NotifyReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NotifyReq> PARSER;

    public static com.google.protobuf.Parser<NotifyReq> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
