// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: check_online_svr/youme_check_online.proto

package YOUMEServiceProtocol;

public final class YoumeCheckOnline {
  private YoumeCheckOnline() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CheckOnlineReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.CheckOnlineReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>required bytes user_id = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>required bytes user_id = 2;</code>
     */
    com.google.protobuf.ByteString getUserId();
  }
  /**
   * <pre>
   * 检查是否在线请求包
   * </pre>
   *
   * Protobuf type {@code YOUMEServiceProtocol.CheckOnlineReq}
   */
  public  static final class CheckOnlineReq extends
      com.google.protobuf.GeneratedMessageLite<
          CheckOnlineReq, CheckOnlineReq.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.CheckOnlineReq)
      CheckOnlineReqOrBuilder {
    private CheckOnlineReq() {
      userId_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
    }

    public static final int USER_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString userId_;
    /**
     * <code>required bytes user_id = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes user_id = 2;</code>
     */
    public com.google.protobuf.ByteString getUserId() {
      return userId_;
    }
    /**
     * <code>required bytes user_id = 2;</code>
     */
    private void setUserId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      userId_ = value;
    }
    /**
     * <code>required bytes user_id = 2;</code>
     */
    private void clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      userId_ = getDefaultInstance().getUserId();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, userId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 检查是否在线请求包
     * </pre>
     *
     * Protobuf type {@code YOUMEServiceProtocol.CheckOnlineReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.CheckOnlineReq)
        YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReqOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       * <code>required bytes user_id = 2;</code>
       */
      public boolean hasUserId() {
        return instance.hasUserId();
      }
      /**
       * <code>required bytes user_id = 2;</code>
       */
      public com.google.protobuf.ByteString getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>required bytes user_id = 2;</code>
       */
      public Builder setUserId(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>required bytes user_id = 2;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.CheckOnlineReq)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasVersion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasUserId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq other = (YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq) arg1;
          version_ = visitor.visitInt(
              hasVersion(), version_,
              other.hasVersion(), other.version_);
          userId_ = visitor.visitByteString(
              hasUserId(), userId_,
              other.hasUserId(), other.userId_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  version_ = input.readInt32();
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000002;
                  userId_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.CheckOnlineReq)
    private static final YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CheckOnlineReq();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CheckOnlineReq> PARSER;

    public static com.google.protobuf.Parser<CheckOnlineReq> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CheckOnlineRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.CheckOnlineRsp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    boolean hasRet();
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    int getRet();

    /**
     * <pre>
     * 0:不在线, 1:在线
     * </pre>
     *
     * <code>required int32 is_online = 3;</code>
     */
    boolean hasIsOnline();
    /**
     * <pre>
     * 0:不在线, 1:在线
     * </pre>
     *
     * <code>required int32 is_online = 3;</code>
     */
    int getIsOnline();
  }
  /**
   * <pre>
   * 检查是否在线应答包
   * </pre>
   *
   * Protobuf type {@code YOUMEServiceProtocol.CheckOnlineRsp}
   */
  public  static final class CheckOnlineRsp extends
      com.google.protobuf.GeneratedMessageLite<
          CheckOnlineRsp, CheckOnlineRsp.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.CheckOnlineRsp)
      CheckOnlineRspOrBuilder {
    private CheckOnlineRsp() {
    }
    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
    }

    public static final int RET_FIELD_NUMBER = 2;
    private int ret_;
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    public int getRet() {
      return ret_;
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    private void setRet(int value) {
      bitField0_ |= 0x00000002;
      ret_ = value;
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    private void clearRet() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ret_ = 0;
    }

    public static final int IS_ONLINE_FIELD_NUMBER = 3;
    private int isOnline_;
    /**
     * <pre>
     * 0:不在线, 1:在线
     * </pre>
     *
     * <code>required int32 is_online = 3;</code>
     */
    public boolean hasIsOnline() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 0:不在线, 1:在线
     * </pre>
     *
     * <code>required int32 is_online = 3;</code>
     */
    public int getIsOnline() {
      return isOnline_;
    }
    /**
     * <pre>
     * 0:不在线, 1:在线
     * </pre>
     *
     * <code>required int32 is_online = 3;</code>
     */
    private void setIsOnline(int value) {
      bitField0_ |= 0x00000004;
      isOnline_ = value;
    }
    /**
     * <pre>
     * 0:不在线, 1:在线
     * </pre>
     *
     * <code>required int32 is_online = 3;</code>
     */
    private void clearIsOnline() {
      bitField0_ = (bitField0_ & ~0x00000004);
      isOnline_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ret_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, isOnline_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ret_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, isOnline_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 检查是否在线应答包
     * </pre>
     *
     * Protobuf type {@code YOUMEServiceProtocol.CheckOnlineRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.CheckOnlineRsp)
        YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRspOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public boolean hasRet() {
        return instance.hasRet();
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public int getRet() {
        return instance.getRet();
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public Builder setRet(int value) {
        copyOnWrite();
        instance.setRet(value);
        return this;
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public Builder clearRet() {
        copyOnWrite();
        instance.clearRet();
        return this;
      }

      /**
       * <pre>
       * 0:不在线, 1:在线
       * </pre>
       *
       * <code>required int32 is_online = 3;</code>
       */
      public boolean hasIsOnline() {
        return instance.hasIsOnline();
      }
      /**
       * <pre>
       * 0:不在线, 1:在线
       * </pre>
       *
       * <code>required int32 is_online = 3;</code>
       */
      public int getIsOnline() {
        return instance.getIsOnline();
      }
      /**
       * <pre>
       * 0:不在线, 1:在线
       * </pre>
       *
       * <code>required int32 is_online = 3;</code>
       */
      public Builder setIsOnline(int value) {
        copyOnWrite();
        instance.setIsOnline(value);
        return this;
      }
      /**
       * <pre>
       * 0:不在线, 1:在线
       * </pre>
       *
       * <code>required int32 is_online = 3;</code>
       */
      public Builder clearIsOnline() {
        copyOnWrite();
        instance.clearIsOnline();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.CheckOnlineRsp)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasVersion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasRet()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasIsOnline()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp other = (YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp) arg1;
          version_ = visitor.visitInt(
              hasVersion(), version_,
              other.hasVersion(), other.version_);
          ret_ = visitor.visitInt(
              hasRet(), ret_,
              other.hasRet(), other.ret_);
          isOnline_ = visitor.visitInt(
              hasIsOnline(), isOnline_,
              other.hasIsOnline(), other.isOnline_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  version_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  ret_ = input.readInt32();
                  break;
                }
                case 24: {
                  bitField0_ |= 0x00000004;
                  isOnline_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.CheckOnlineRsp)
    private static final YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CheckOnlineRsp();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeCheckOnline.CheckOnlineRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CheckOnlineRsp> PARSER;

    public static com.google.protobuf.Parser<CheckOnlineRsp> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
