// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sndmsg_svr/youme_sndmsg.proto

package YOUMEServiceProtocol;

public final class YoumeSndmsg {
  private YoumeSndmsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RecverListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.RecverList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated bytes recver_id = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getRecverIdList();
    /**
     * <code>repeated bytes recver_id = 1;</code>
     */
    int getRecverIdCount();
    /**
     * <code>repeated bytes recver_id = 1;</code>
     */
    com.google.protobuf.ByteString getRecverId(int index);
  }
  /**
   * <pre>
   * 群发的接收者ID列表
   * </pre>
   *
   * Protobuf type {@code YOUMEServiceProtocol.RecverList}
   */
  public  static final class RecverList extends
      com.google.protobuf.GeneratedMessageLite<
          RecverList, RecverList.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.RecverList)
      RecverListOrBuilder {
    private RecverList() {
      recverId_ = emptyProtobufList();
    }
    public static final int RECVER_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> recverId_;
    /**
     * <code>repeated bytes recver_id = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getRecverIdList() {
      return recverId_;
    }
    /**
     * <code>repeated bytes recver_id = 1;</code>
     */
    public int getRecverIdCount() {
      return recverId_.size();
    }
    /**
     * <code>repeated bytes recver_id = 1;</code>
     */
    public com.google.protobuf.ByteString getRecverId(int index) {
      return recverId_.get(index);
    }
    private void ensureRecverIdIsMutable() {
      if (!recverId_.isModifiable()) {
        recverId_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(recverId_);
       }
    }
    /**
     * <code>repeated bytes recver_id = 1;</code>
     */
    private void setRecverId(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRecverIdIsMutable();
      recverId_.set(index, value);
    }
    /**
     * <code>repeated bytes recver_id = 1;</code>
     */
    private void addRecverId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRecverIdIsMutable();
      recverId_.add(value);
    }
    /**
     * <code>repeated bytes recver_id = 1;</code>
     */
    private void addAllRecverId(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureRecverIdIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, recverId_);
    }
    /**
     * <code>repeated bytes recver_id = 1;</code>
     */
    private void clearRecverId() {
      recverId_ = emptyProtobufList();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < recverId_.size(); i++) {
        output.writeBytes(1, recverId_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < recverId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(recverId_.get(i));
        }
        size += dataSize;
        size += 1 * getRecverIdList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeSndmsg.RecverList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RecverList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RecverList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RecverList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RecverList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RecverList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RecverList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RecverList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RecverList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RecverList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeSndmsg.RecverList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 群发的接收者ID列表
     * </pre>
     *
     * Protobuf type {@code YOUMEServiceProtocol.RecverList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeSndmsg.RecverList, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.RecverList)
        YOUMEServiceProtocol.YoumeSndmsg.RecverListOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeSndmsg.RecverList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated bytes recver_id = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getRecverIdList() {
        return java.util.Collections.unmodifiableList(
            instance.getRecverIdList());
      }
      /**
       * <code>repeated bytes recver_id = 1;</code>
       */
      public int getRecverIdCount() {
        return instance.getRecverIdCount();
      }
      /**
       * <code>repeated bytes recver_id = 1;</code>
       */
      public com.google.protobuf.ByteString getRecverId(int index) {
        return instance.getRecverId(index);
      }
      /**
       * <code>repeated bytes recver_id = 1;</code>
       */
      public Builder setRecverId(
          int index, com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRecverId(index, value);
        return this;
      }
      /**
       * <code>repeated bytes recver_id = 1;</code>
       */
      public Builder addRecverId(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addRecverId(value);
        return this;
      }
      /**
       * <code>repeated bytes recver_id = 1;</code>
       */
      public Builder addAllRecverId(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        copyOnWrite();
        instance.addAllRecverId(values);
        return this;
      }
      /**
       * <code>repeated bytes recver_id = 1;</code>
       */
      public Builder clearRecverId() {
        copyOnWrite();
        instance.clearRecverId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.RecverList)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeSndmsg.RecverList();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          recverId_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeSndmsg.RecverList other = (YOUMEServiceProtocol.YoumeSndmsg.RecverList) arg1;
          recverId_= visitor.visitList(recverId_, other.recverId_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!recverId_.isModifiable()) {
                    recverId_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(recverId_);
                  }
                  recverId_.add(input.readBytes());
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeSndmsg.RecverList.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.RecverList)
    private static final YOUMEServiceProtocol.YoumeSndmsg.RecverList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RecverList();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeSndmsg.RecverList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RecverList> PARSER;

    public static com.google.protobuf.Parser<RecverList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SendMsgReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.SendMsgReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>required int32 chat_type = 2;</code>
     */
    boolean hasChatType();
    /**
     * <code>required int32 chat_type = 2;</code>
     */
    int getChatType();

    /**
     * <code>required bytes recv_id = 3;</code>
     */
    boolean hasRecvId();
    /**
     * <code>required bytes recv_id = 3;</code>
     */
    com.google.protobuf.ByteString getRecvId();

    /**
     * <code>required bytes msg_content = 4;</code>
     */
    boolean hasMsgContent();
    /**
     * <code>required bytes msg_content = 4;</code>
     */
    com.google.protobuf.ByteString getMsgContent();

    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
     */
    boolean hasComment();
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
     */
    YOUMECommonProtocol.YoumeComm.MsgComment getComment();
  }
  /**
   * <pre>
   * 消息请求包
   * </pre>
   *
   * Protobuf type {@code YOUMEServiceProtocol.SendMsgReq}
   */
  public  static final class SendMsgReq extends
      com.google.protobuf.GeneratedMessageLite<
          SendMsgReq, SendMsgReq.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.SendMsgReq)
      SendMsgReqOrBuilder {
    private SendMsgReq() {
      recvId_ = com.google.protobuf.ByteString.EMPTY;
      msgContent_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
    }

    public static final int CHAT_TYPE_FIELD_NUMBER = 2;
    private int chatType_;
    /**
     * <code>required int32 chat_type = 2;</code>
     */
    public boolean hasChatType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 chat_type = 2;</code>
     */
    public int getChatType() {
      return chatType_;
    }
    /**
     * <code>required int32 chat_type = 2;</code>
     */
    private void setChatType(int value) {
      bitField0_ |= 0x00000002;
      chatType_ = value;
    }
    /**
     * <code>required int32 chat_type = 2;</code>
     */
    private void clearChatType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      chatType_ = 0;
    }

    public static final int RECV_ID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString recvId_;
    /**
     * <code>required bytes recv_id = 3;</code>
     */
    public boolean hasRecvId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes recv_id = 3;</code>
     */
    public com.google.protobuf.ByteString getRecvId() {
      return recvId_;
    }
    /**
     * <code>required bytes recv_id = 3;</code>
     */
    private void setRecvId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      recvId_ = value;
    }
    /**
     * <code>required bytes recv_id = 3;</code>
     */
    private void clearRecvId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      recvId_ = getDefaultInstance().getRecvId();
    }

    public static final int MSG_CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString msgContent_;
    /**
     * <code>required bytes msg_content = 4;</code>
     */
    public boolean hasMsgContent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes msg_content = 4;</code>
     */
    public com.google.protobuf.ByteString getMsgContent() {
      return msgContent_;
    }
    /**
     * <code>required bytes msg_content = 4;</code>
     */
    private void setMsgContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      msgContent_ = value;
    }
    /**
     * <code>required bytes msg_content = 4;</code>
     */
    private void clearMsgContent() {
      bitField0_ = (bitField0_ & ~0x00000008);
      msgContent_ = getDefaultInstance().getMsgContent();
    }

    public static final int COMMENT_FIELD_NUMBER = 5;
    private YOUMECommonProtocol.YoumeComm.MsgComment comment_;
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
     */
    public boolean hasComment() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
     */
    public YOUMECommonProtocol.YoumeComm.MsgComment getComment() {
      return comment_ == null ? YOUMECommonProtocol.YoumeComm.MsgComment.getDefaultInstance() : comment_;
    }
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
     */
    private void setComment(YOUMECommonProtocol.YoumeComm.MsgComment value) {
      if (value == null) {
        throw new NullPointerException();
      }
      comment_ = value;
      bitField0_ |= 0x00000010;
      }
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
     */
    private void setComment(
        YOUMECommonProtocol.YoumeComm.MsgComment.Builder builderForValue) {
      comment_ = builderForValue.build();
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
     */
    private void mergeComment(YOUMECommonProtocol.YoumeComm.MsgComment value) {
      if (comment_ != null &&
          comment_ != YOUMECommonProtocol.YoumeComm.MsgComment.getDefaultInstance()) {
        comment_ =
          YOUMECommonProtocol.YoumeComm.MsgComment.newBuilder(comment_).mergeFrom(value).buildPartial();
      } else {
        comment_ = value;
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
     */
    private void clearComment() {  comment_ = null;
      bitField0_ = (bitField0_ & ~0x00000010);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, chatType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, recvId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, msgContent_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, getComment());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chatType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, recvId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, msgContent_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getComment());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 消息请求包
     * </pre>
     *
     * Protobuf type {@code YOUMEServiceProtocol.SendMsgReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.SendMsgReq)
        YOUMEServiceProtocol.YoumeSndmsg.SendMsgReqOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       * <code>required int32 chat_type = 2;</code>
       */
      public boolean hasChatType() {
        return instance.hasChatType();
      }
      /**
       * <code>required int32 chat_type = 2;</code>
       */
      public int getChatType() {
        return instance.getChatType();
      }
      /**
       * <code>required int32 chat_type = 2;</code>
       */
      public Builder setChatType(int value) {
        copyOnWrite();
        instance.setChatType(value);
        return this;
      }
      /**
       * <code>required int32 chat_type = 2;</code>
       */
      public Builder clearChatType() {
        copyOnWrite();
        instance.clearChatType();
        return this;
      }

      /**
       * <code>required bytes recv_id = 3;</code>
       */
      public boolean hasRecvId() {
        return instance.hasRecvId();
      }
      /**
       * <code>required bytes recv_id = 3;</code>
       */
      public com.google.protobuf.ByteString getRecvId() {
        return instance.getRecvId();
      }
      /**
       * <code>required bytes recv_id = 3;</code>
       */
      public Builder setRecvId(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRecvId(value);
        return this;
      }
      /**
       * <code>required bytes recv_id = 3;</code>
       */
      public Builder clearRecvId() {
        copyOnWrite();
        instance.clearRecvId();
        return this;
      }

      /**
       * <code>required bytes msg_content = 4;</code>
       */
      public boolean hasMsgContent() {
        return instance.hasMsgContent();
      }
      /**
       * <code>required bytes msg_content = 4;</code>
       */
      public com.google.protobuf.ByteString getMsgContent() {
        return instance.getMsgContent();
      }
      /**
       * <code>required bytes msg_content = 4;</code>
       */
      public Builder setMsgContent(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMsgContent(value);
        return this;
      }
      /**
       * <code>required bytes msg_content = 4;</code>
       */
      public Builder clearMsgContent() {
        copyOnWrite();
        instance.clearMsgContent();
        return this;
      }

      /**
       * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
       */
      public boolean hasComment() {
        return instance.hasComment();
      }
      /**
       * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
       */
      public YOUMECommonProtocol.YoumeComm.MsgComment getComment() {
        return instance.getComment();
      }
      /**
       * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
       */
      public Builder setComment(YOUMECommonProtocol.YoumeComm.MsgComment value) {
        copyOnWrite();
        instance.setComment(value);
        return this;
        }
      /**
       * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
       */
      public Builder setComment(
          YOUMECommonProtocol.YoumeComm.MsgComment.Builder builderForValue) {
        copyOnWrite();
        instance.setComment(builderForValue);
        return this;
      }
      /**
       * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
       */
      public Builder mergeComment(YOUMECommonProtocol.YoumeComm.MsgComment value) {
        copyOnWrite();
        instance.mergeComment(value);
        return this;
      }
      /**
       * <code>optional .YOUMECommonProtocol.MsgComment comment = 5;</code>
       */
      public Builder clearComment() {  copyOnWrite();
        instance.clearComment();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.SendMsgReq)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasVersion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasChatType()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasRecvId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasMsgContent()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (hasComment()) {
            if (!getComment().isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq other = (YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq) arg1;
          version_ = visitor.visitInt(
              hasVersion(), version_,
              other.hasVersion(), other.version_);
          chatType_ = visitor.visitInt(
              hasChatType(), chatType_,
              other.hasChatType(), other.chatType_);
          recvId_ = visitor.visitByteString(
              hasRecvId(), recvId_,
              other.hasRecvId(), other.recvId_);
          msgContent_ = visitor.visitByteString(
              hasMsgContent(), msgContent_,
              other.hasMsgContent(), other.msgContent_);
          comment_ = visitor.visitMessage(comment_, other.comment_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  version_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  chatType_ = input.readInt32();
                  break;
                }
                case 26: {
                  bitField0_ |= 0x00000004;
                  recvId_ = input.readBytes();
                  break;
                }
                case 34: {
                  bitField0_ |= 0x00000008;
                  msgContent_ = input.readBytes();
                  break;
                }
                case 42: {
                  YOUMECommonProtocol.YoumeComm.MsgComment.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    subBuilder = comment_.toBuilder();
                  }
                  comment_ = input.readMessage(YOUMECommonProtocol.YoumeComm.MsgComment.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(comment_);
                    comment_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000010;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.SendMsgReq)
    private static final YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SendMsgReq();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SendMsgReq> PARSER;

    public static com.google.protobuf.Parser<SendMsgReq> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SendMsgRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.SendMsgRsp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    boolean hasRet();
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    int getRet();

    /**
     * <pre>
     * 发送成功后, 服务器返回的消息ID
     * </pre>
     *
     * <code>required uint64 svr_msgid = 3;</code>
     */
    boolean hasSvrMsgid();
    /**
     * <pre>
     * 发送成功后, 服务器返回的消息ID
     * </pre>
     *
     * <code>required uint64 svr_msgid = 3;</code>
     */
    long getSvrMsgid();

    /**
     * <code>optional bytes ret_info = 4;</code>
     */
    boolean hasRetInfo();
    /**
     * <code>optional bytes ret_info = 4;</code>
     */
    com.google.protobuf.ByteString getRetInfo();

    /**
     * <pre>
     * 封禁过期时间
     * </pre>
     *
     * <code>optional uint64 expire_time = 5;</code>
     */
    boolean hasExpireTime();
    /**
     * <pre>
     * 封禁过期时间
     * </pre>
     *
     * <code>optional uint64 expire_time = 5;</code>
     */
    long getExpireTime();

    /**
     * <pre>
     * 房间是否被封禁
     * </pre>
     *
     * <code>optional bool forbid_room = 6;</code>
     */
    boolean hasForbidRoom();
    /**
     * <pre>
     * 房间是否被封禁
     * </pre>
     *
     * <code>optional bool forbid_room = 6;</code>
     */
    boolean getForbidRoom();

    /**
     * <pre>
     * 封禁类型
     * </pre>
     *
     * <code>optional int32 reason_type = 7;</code>
     */
    boolean hasReasonType();
    /**
     * <pre>
     * 封禁类型
     * </pre>
     *
     * <code>optional int32 reason_type = 7;</code>
     */
    int getReasonType();

    /**
     * <pre>
     * 封禁原因
     * </pre>
     *
     * <code>optional string reason = 8;</code>
     */
    boolean hasReason();
    /**
     * <pre>
     * 封禁原因
     * </pre>
     *
     * <code>optional string reason = 8;</code>
     */
    java.lang.String getReason();
    /**
     * <pre>
     * 封禁原因
     * </pre>
     *
     * <code>optional string reason = 8;</code>
     */
    com.google.protobuf.ByteString
        getReasonBytes();
  }
  /**
   * <pre>
   * 消息应答包
   * </pre>
   *
   * Protobuf type {@code YOUMEServiceProtocol.SendMsgRsp}
   */
  public  static final class SendMsgRsp extends
      com.google.protobuf.GeneratedMessageLite<
          SendMsgRsp, SendMsgRsp.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.SendMsgRsp)
      SendMsgRspOrBuilder {
    private SendMsgRsp() {
      retInfo_ = com.google.protobuf.ByteString.EMPTY;
      reason_ = "";
    }
    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
    }

    public static final int RET_FIELD_NUMBER = 2;
    private int ret_;
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    public int getRet() {
      return ret_;
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    private void setRet(int value) {
      bitField0_ |= 0x00000002;
      ret_ = value;
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    private void clearRet() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ret_ = 0;
    }

    public static final int SVR_MSGID_FIELD_NUMBER = 3;
    private long svrMsgid_;
    /**
     * <pre>
     * 发送成功后, 服务器返回的消息ID
     * </pre>
     *
     * <code>required uint64 svr_msgid = 3;</code>
     */
    public boolean hasSvrMsgid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 发送成功后, 服务器返回的消息ID
     * </pre>
     *
     * <code>required uint64 svr_msgid = 3;</code>
     */
    public long getSvrMsgid() {
      return svrMsgid_;
    }
    /**
     * <pre>
     * 发送成功后, 服务器返回的消息ID
     * </pre>
     *
     * <code>required uint64 svr_msgid = 3;</code>
     */
    private void setSvrMsgid(long value) {
      bitField0_ |= 0x00000004;
      svrMsgid_ = value;
    }
    /**
     * <pre>
     * 发送成功后, 服务器返回的消息ID
     * </pre>
     *
     * <code>required uint64 svr_msgid = 3;</code>
     */
    private void clearSvrMsgid() {
      bitField0_ = (bitField0_ & ~0x00000004);
      svrMsgid_ = 0L;
    }

    public static final int RET_INFO_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString retInfo_;
    /**
     * <code>optional bytes ret_info = 4;</code>
     */
    public boolean hasRetInfo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes ret_info = 4;</code>
     */
    public com.google.protobuf.ByteString getRetInfo() {
      return retInfo_;
    }
    /**
     * <code>optional bytes ret_info = 4;</code>
     */
    private void setRetInfo(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      retInfo_ = value;
    }
    /**
     * <code>optional bytes ret_info = 4;</code>
     */
    private void clearRetInfo() {
      bitField0_ = (bitField0_ & ~0x00000008);
      retInfo_ = getDefaultInstance().getRetInfo();
    }

    public static final int EXPIRE_TIME_FIELD_NUMBER = 5;
    private long expireTime_;
    /**
     * <pre>
     * 封禁过期时间
     * </pre>
     *
     * <code>optional uint64 expire_time = 5;</code>
     */
    public boolean hasExpireTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * 封禁过期时间
     * </pre>
     *
     * <code>optional uint64 expire_time = 5;</code>
     */
    public long getExpireTime() {
      return expireTime_;
    }
    /**
     * <pre>
     * 封禁过期时间
     * </pre>
     *
     * <code>optional uint64 expire_time = 5;</code>
     */
    private void setExpireTime(long value) {
      bitField0_ |= 0x00000010;
      expireTime_ = value;
    }
    /**
     * <pre>
     * 封禁过期时间
     * </pre>
     *
     * <code>optional uint64 expire_time = 5;</code>
     */
    private void clearExpireTime() {
      bitField0_ = (bitField0_ & ~0x00000010);
      expireTime_ = 0L;
    }

    public static final int FORBID_ROOM_FIELD_NUMBER = 6;
    private boolean forbidRoom_;
    /**
     * <pre>
     * 房间是否被封禁
     * </pre>
     *
     * <code>optional bool forbid_room = 6;</code>
     */
    public boolean hasForbidRoom() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * 房间是否被封禁
     * </pre>
     *
     * <code>optional bool forbid_room = 6;</code>
     */
    public boolean getForbidRoom() {
      return forbidRoom_;
    }
    /**
     * <pre>
     * 房间是否被封禁
     * </pre>
     *
     * <code>optional bool forbid_room = 6;</code>
     */
    private void setForbidRoom(boolean value) {
      bitField0_ |= 0x00000020;
      forbidRoom_ = value;
    }
    /**
     * <pre>
     * 房间是否被封禁
     * </pre>
     *
     * <code>optional bool forbid_room = 6;</code>
     */
    private void clearForbidRoom() {
      bitField0_ = (bitField0_ & ~0x00000020);
      forbidRoom_ = false;
    }

    public static final int REASON_TYPE_FIELD_NUMBER = 7;
    private int reasonType_;
    /**
     * <pre>
     * 封禁类型
     * </pre>
     *
     * <code>optional int32 reason_type = 7;</code>
     */
    public boolean hasReasonType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * 封禁类型
     * </pre>
     *
     * <code>optional int32 reason_type = 7;</code>
     */
    public int getReasonType() {
      return reasonType_;
    }
    /**
     * <pre>
     * 封禁类型
     * </pre>
     *
     * <code>optional int32 reason_type = 7;</code>
     */
    private void setReasonType(int value) {
      bitField0_ |= 0x00000040;
      reasonType_ = value;
    }
    /**
     * <pre>
     * 封禁类型
     * </pre>
     *
     * <code>optional int32 reason_type = 7;</code>
     */
    private void clearReasonType() {
      bitField0_ = (bitField0_ & ~0x00000040);
      reasonType_ = 0;
    }

    public static final int REASON_FIELD_NUMBER = 8;
    private java.lang.String reason_;
    /**
     * <pre>
     * 封禁原因
     * </pre>
     *
     * <code>optional string reason = 8;</code>
     */
    public boolean hasReason() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     * 封禁原因
     * </pre>
     *
     * <code>optional string reason = 8;</code>
     */
    public java.lang.String getReason() {
      return reason_;
    }
    /**
     * <pre>
     * 封禁原因
     * </pre>
     *
     * <code>optional string reason = 8;</code>
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(reason_);
    }
    /**
     * <pre>
     * 封禁原因
     * </pre>
     *
     * <code>optional string reason = 8;</code>
     */
    private void setReason(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      reason_ = value;
    }
    /**
     * <pre>
     * 封禁原因
     * </pre>
     *
     * <code>optional string reason = 8;</code>
     */
    private void clearReason() {
      bitField0_ = (bitField0_ & ~0x00000080);
      reason_ = getDefaultInstance().getReason();
    }
    /**
     * <pre>
     * 封禁原因
     * </pre>
     *
     * <code>optional string reason = 8;</code>
     */
    private void setReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      reason_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ret_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, svrMsgid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, retInfo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, expireTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, forbidRoom_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, reasonType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeString(8, getReason());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ret_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, svrMsgid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, retInfo_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, expireTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, forbidRoom_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, reasonType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getReason());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 消息应答包
     * </pre>
     *
     * Protobuf type {@code YOUMEServiceProtocol.SendMsgRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.SendMsgRsp)
        YOUMEServiceProtocol.YoumeSndmsg.SendMsgRspOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public boolean hasRet() {
        return instance.hasRet();
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public int getRet() {
        return instance.getRet();
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public Builder setRet(int value) {
        copyOnWrite();
        instance.setRet(value);
        return this;
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public Builder clearRet() {
        copyOnWrite();
        instance.clearRet();
        return this;
      }

      /**
       * <pre>
       * 发送成功后, 服务器返回的消息ID
       * </pre>
       *
       * <code>required uint64 svr_msgid = 3;</code>
       */
      public boolean hasSvrMsgid() {
        return instance.hasSvrMsgid();
      }
      /**
       * <pre>
       * 发送成功后, 服务器返回的消息ID
       * </pre>
       *
       * <code>required uint64 svr_msgid = 3;</code>
       */
      public long getSvrMsgid() {
        return instance.getSvrMsgid();
      }
      /**
       * <pre>
       * 发送成功后, 服务器返回的消息ID
       * </pre>
       *
       * <code>required uint64 svr_msgid = 3;</code>
       */
      public Builder setSvrMsgid(long value) {
        copyOnWrite();
        instance.setSvrMsgid(value);
        return this;
      }
      /**
       * <pre>
       * 发送成功后, 服务器返回的消息ID
       * </pre>
       *
       * <code>required uint64 svr_msgid = 3;</code>
       */
      public Builder clearSvrMsgid() {
        copyOnWrite();
        instance.clearSvrMsgid();
        return this;
      }

      /**
       * <code>optional bytes ret_info = 4;</code>
       */
      public boolean hasRetInfo() {
        return instance.hasRetInfo();
      }
      /**
       * <code>optional bytes ret_info = 4;</code>
       */
      public com.google.protobuf.ByteString getRetInfo() {
        return instance.getRetInfo();
      }
      /**
       * <code>optional bytes ret_info = 4;</code>
       */
      public Builder setRetInfo(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRetInfo(value);
        return this;
      }
      /**
       * <code>optional bytes ret_info = 4;</code>
       */
      public Builder clearRetInfo() {
        copyOnWrite();
        instance.clearRetInfo();
        return this;
      }

      /**
       * <pre>
       * 封禁过期时间
       * </pre>
       *
       * <code>optional uint64 expire_time = 5;</code>
       */
      public boolean hasExpireTime() {
        return instance.hasExpireTime();
      }
      /**
       * <pre>
       * 封禁过期时间
       * </pre>
       *
       * <code>optional uint64 expire_time = 5;</code>
       */
      public long getExpireTime() {
        return instance.getExpireTime();
      }
      /**
       * <pre>
       * 封禁过期时间
       * </pre>
       *
       * <code>optional uint64 expire_time = 5;</code>
       */
      public Builder setExpireTime(long value) {
        copyOnWrite();
        instance.setExpireTime(value);
        return this;
      }
      /**
       * <pre>
       * 封禁过期时间
       * </pre>
       *
       * <code>optional uint64 expire_time = 5;</code>
       */
      public Builder clearExpireTime() {
        copyOnWrite();
        instance.clearExpireTime();
        return this;
      }

      /**
       * <pre>
       * 房间是否被封禁
       * </pre>
       *
       * <code>optional bool forbid_room = 6;</code>
       */
      public boolean hasForbidRoom() {
        return instance.hasForbidRoom();
      }
      /**
       * <pre>
       * 房间是否被封禁
       * </pre>
       *
       * <code>optional bool forbid_room = 6;</code>
       */
      public boolean getForbidRoom() {
        return instance.getForbidRoom();
      }
      /**
       * <pre>
       * 房间是否被封禁
       * </pre>
       *
       * <code>optional bool forbid_room = 6;</code>
       */
      public Builder setForbidRoom(boolean value) {
        copyOnWrite();
        instance.setForbidRoom(value);
        return this;
      }
      /**
       * <pre>
       * 房间是否被封禁
       * </pre>
       *
       * <code>optional bool forbid_room = 6;</code>
       */
      public Builder clearForbidRoom() {
        copyOnWrite();
        instance.clearForbidRoom();
        return this;
      }

      /**
       * <pre>
       * 封禁类型
       * </pre>
       *
       * <code>optional int32 reason_type = 7;</code>
       */
      public boolean hasReasonType() {
        return instance.hasReasonType();
      }
      /**
       * <pre>
       * 封禁类型
       * </pre>
       *
       * <code>optional int32 reason_type = 7;</code>
       */
      public int getReasonType() {
        return instance.getReasonType();
      }
      /**
       * <pre>
       * 封禁类型
       * </pre>
       *
       * <code>optional int32 reason_type = 7;</code>
       */
      public Builder setReasonType(int value) {
        copyOnWrite();
        instance.setReasonType(value);
        return this;
      }
      /**
       * <pre>
       * 封禁类型
       * </pre>
       *
       * <code>optional int32 reason_type = 7;</code>
       */
      public Builder clearReasonType() {
        copyOnWrite();
        instance.clearReasonType();
        return this;
      }

      /**
       * <pre>
       * 封禁原因
       * </pre>
       *
       * <code>optional string reason = 8;</code>
       */
      public boolean hasReason() {
        return instance.hasReason();
      }
      /**
       * <pre>
       * 封禁原因
       * </pre>
       *
       * <code>optional string reason = 8;</code>
       */
      public java.lang.String getReason() {
        return instance.getReason();
      }
      /**
       * <pre>
       * 封禁原因
       * </pre>
       *
       * <code>optional string reason = 8;</code>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        return instance.getReasonBytes();
      }
      /**
       * <pre>
       * 封禁原因
       * </pre>
       *
       * <code>optional string reason = 8;</code>
       */
      public Builder setReason(
          java.lang.String value) {
        copyOnWrite();
        instance.setReason(value);
        return this;
      }
      /**
       * <pre>
       * 封禁原因
       * </pre>
       *
       * <code>optional string reason = 8;</code>
       */
      public Builder clearReason() {
        copyOnWrite();
        instance.clearReason();
        return this;
      }
      /**
       * <pre>
       * 封禁原因
       * </pre>
       *
       * <code>optional string reason = 8;</code>
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setReasonBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.SendMsgRsp)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasVersion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasRet()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasSvrMsgid()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp other = (YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp) arg1;
          version_ = visitor.visitInt(
              hasVersion(), version_,
              other.hasVersion(), other.version_);
          ret_ = visitor.visitInt(
              hasRet(), ret_,
              other.hasRet(), other.ret_);
          svrMsgid_ = visitor.visitLong(
              hasSvrMsgid(), svrMsgid_,
              other.hasSvrMsgid(), other.svrMsgid_);
          retInfo_ = visitor.visitByteString(
              hasRetInfo(), retInfo_,
              other.hasRetInfo(), other.retInfo_);
          expireTime_ = visitor.visitLong(
              hasExpireTime(), expireTime_,
              other.hasExpireTime(), other.expireTime_);
          forbidRoom_ = visitor.visitBoolean(
              hasForbidRoom(), forbidRoom_,
              other.hasForbidRoom(), other.forbidRoom_);
          reasonType_ = visitor.visitInt(
              hasReasonType(), reasonType_,
              other.hasReasonType(), other.reasonType_);
          reason_ = visitor.visitString(
              hasReason(), reason_,
              other.hasReason(), other.reason_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  version_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  ret_ = input.readInt32();
                  break;
                }
                case 24: {
                  bitField0_ |= 0x00000004;
                  svrMsgid_ = input.readUInt64();
                  break;
                }
                case 34: {
                  bitField0_ |= 0x00000008;
                  retInfo_ = input.readBytes();
                  break;
                }
                case 40: {
                  bitField0_ |= 0x00000010;
                  expireTime_ = input.readUInt64();
                  break;
                }
                case 48: {
                  bitField0_ |= 0x00000020;
                  forbidRoom_ = input.readBool();
                  break;
                }
                case 56: {
                  bitField0_ |= 0x00000040;
                  reasonType_ = input.readInt32();
                  break;
                }
                case 66: {
                  String s = input.readString();
                  bitField0_ |= 0x00000080;
                  reason_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.SendMsgRsp)
    private static final YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SendMsgRsp();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeSndmsg.SendMsgRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SendMsgRsp> PARSER;

    public static com.google.protobuf.Parser<SendMsgRsp> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RoomMsgNoticeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.RoomMsgNotice)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>required bytes sender_id = 2;</code>
     */
    boolean hasSenderId();
    /**
     * <code>required bytes sender_id = 2;</code>
     */
    com.google.protobuf.ByteString getSenderId();

    /**
     * <code>required bytes room_name = 3;</code>
     */
    boolean hasRoomName();
    /**
     * <code>required bytes room_name = 3;</code>
     */
    com.google.protobuf.ByteString getRoomName();

    /**
     * <code>required int32 notice_property = 4;</code>
     */
    boolean hasNoticeProperty();
    /**
     * <code>required int32 notice_property = 4;</code>
     */
    int getNoticeProperty();

    /**
     * <code>optional bytes msg_content = 5;</code>
     */
    boolean hasMsgContent();
    /**
     * <code>optional bytes msg_content = 5;</code>
     */
    com.google.protobuf.ByteString getMsgContent();

    /**
     * <code>optional bool check_mask = 6;</code>
     */
    boolean hasCheckMask();
    /**
     * <code>optional bool check_mask = 6;</code>
     */
    boolean getCheckMask();
  }
  /**
   * <pre>
   * 消息事件
   * </pre>
   *
   * Protobuf type {@code YOUMEServiceProtocol.RoomMsgNotice}
   */
  public  static final class RoomMsgNotice extends
      com.google.protobuf.GeneratedMessageLite<
          RoomMsgNotice, RoomMsgNotice.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.RoomMsgNotice)
      RoomMsgNoticeOrBuilder {
    private RoomMsgNotice() {
      senderId_ = com.google.protobuf.ByteString.EMPTY;
      roomName_ = com.google.protobuf.ByteString.EMPTY;
      msgContent_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
    }

    public static final int SENDER_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString senderId_;
    /**
     * <code>required bytes sender_id = 2;</code>
     */
    public boolean hasSenderId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes sender_id = 2;</code>
     */
    public com.google.protobuf.ByteString getSenderId() {
      return senderId_;
    }
    /**
     * <code>required bytes sender_id = 2;</code>
     */
    private void setSenderId(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      senderId_ = value;
    }
    /**
     * <code>required bytes sender_id = 2;</code>
     */
    private void clearSenderId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      senderId_ = getDefaultInstance().getSenderId();
    }

    public static final int ROOM_NAME_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString roomName_;
    /**
     * <code>required bytes room_name = 3;</code>
     */
    public boolean hasRoomName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes room_name = 3;</code>
     */
    public com.google.protobuf.ByteString getRoomName() {
      return roomName_;
    }
    /**
     * <code>required bytes room_name = 3;</code>
     */
    private void setRoomName(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      roomName_ = value;
    }
    /**
     * <code>required bytes room_name = 3;</code>
     */
    private void clearRoomName() {
      bitField0_ = (bitField0_ & ~0x00000004);
      roomName_ = getDefaultInstance().getRoomName();
    }

    public static final int NOTICE_PROPERTY_FIELD_NUMBER = 4;
    private int noticeProperty_;
    /**
     * <code>required int32 notice_property = 4;</code>
     */
    public boolean hasNoticeProperty() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 notice_property = 4;</code>
     */
    public int getNoticeProperty() {
      return noticeProperty_;
    }
    /**
     * <code>required int32 notice_property = 4;</code>
     */
    private void setNoticeProperty(int value) {
      bitField0_ |= 0x00000008;
      noticeProperty_ = value;
    }
    /**
     * <code>required int32 notice_property = 4;</code>
     */
    private void clearNoticeProperty() {
      bitField0_ = (bitField0_ & ~0x00000008);
      noticeProperty_ = 0;
    }

    public static final int MSG_CONTENT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString msgContent_;
    /**
     * <code>optional bytes msg_content = 5;</code>
     */
    public boolean hasMsgContent() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes msg_content = 5;</code>
     */
    public com.google.protobuf.ByteString getMsgContent() {
      return msgContent_;
    }
    /**
     * <code>optional bytes msg_content = 5;</code>
     */
    private void setMsgContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      msgContent_ = value;
    }
    /**
     * <code>optional bytes msg_content = 5;</code>
     */
    private void clearMsgContent() {
      bitField0_ = (bitField0_ & ~0x00000010);
      msgContent_ = getDefaultInstance().getMsgContent();
    }

    public static final int CHECK_MASK_FIELD_NUMBER = 6;
    private boolean checkMask_;
    /**
     * <code>optional bool check_mask = 6;</code>
     */
    public boolean hasCheckMask() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool check_mask = 6;</code>
     */
    public boolean getCheckMask() {
      return checkMask_;
    }
    /**
     * <code>optional bool check_mask = 6;</code>
     */
    private void setCheckMask(boolean value) {
      bitField0_ |= 0x00000020;
      checkMask_ = value;
    }
    /**
     * <code>optional bool check_mask = 6;</code>
     */
    private void clearCheckMask() {
      bitField0_ = (bitField0_ & ~0x00000020);
      checkMask_ = false;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, senderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, roomName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, noticeProperty_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, msgContent_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, checkMask_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, senderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, roomName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, noticeProperty_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, msgContent_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, checkMask_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 消息事件
     * </pre>
     *
     * Protobuf type {@code YOUMEServiceProtocol.RoomMsgNotice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.RoomMsgNotice)
        YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNoticeOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       * <code>required bytes sender_id = 2;</code>
       */
      public boolean hasSenderId() {
        return instance.hasSenderId();
      }
      /**
       * <code>required bytes sender_id = 2;</code>
       */
      public com.google.protobuf.ByteString getSenderId() {
        return instance.getSenderId();
      }
      /**
       * <code>required bytes sender_id = 2;</code>
       */
      public Builder setSenderId(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSenderId(value);
        return this;
      }
      /**
       * <code>required bytes sender_id = 2;</code>
       */
      public Builder clearSenderId() {
        copyOnWrite();
        instance.clearSenderId();
        return this;
      }

      /**
       * <code>required bytes room_name = 3;</code>
       */
      public boolean hasRoomName() {
        return instance.hasRoomName();
      }
      /**
       * <code>required bytes room_name = 3;</code>
       */
      public com.google.protobuf.ByteString getRoomName() {
        return instance.getRoomName();
      }
      /**
       * <code>required bytes room_name = 3;</code>
       */
      public Builder setRoomName(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRoomName(value);
        return this;
      }
      /**
       * <code>required bytes room_name = 3;</code>
       */
      public Builder clearRoomName() {
        copyOnWrite();
        instance.clearRoomName();
        return this;
      }

      /**
       * <code>required int32 notice_property = 4;</code>
       */
      public boolean hasNoticeProperty() {
        return instance.hasNoticeProperty();
      }
      /**
       * <code>required int32 notice_property = 4;</code>
       */
      public int getNoticeProperty() {
        return instance.getNoticeProperty();
      }
      /**
       * <code>required int32 notice_property = 4;</code>
       */
      public Builder setNoticeProperty(int value) {
        copyOnWrite();
        instance.setNoticeProperty(value);
        return this;
      }
      /**
       * <code>required int32 notice_property = 4;</code>
       */
      public Builder clearNoticeProperty() {
        copyOnWrite();
        instance.clearNoticeProperty();
        return this;
      }

      /**
       * <code>optional bytes msg_content = 5;</code>
       */
      public boolean hasMsgContent() {
        return instance.hasMsgContent();
      }
      /**
       * <code>optional bytes msg_content = 5;</code>
       */
      public com.google.protobuf.ByteString getMsgContent() {
        return instance.getMsgContent();
      }
      /**
       * <code>optional bytes msg_content = 5;</code>
       */
      public Builder setMsgContent(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMsgContent(value);
        return this;
      }
      /**
       * <code>optional bytes msg_content = 5;</code>
       */
      public Builder clearMsgContent() {
        copyOnWrite();
        instance.clearMsgContent();
        return this;
      }

      /**
       * <code>optional bool check_mask = 6;</code>
       */
      public boolean hasCheckMask() {
        return instance.hasCheckMask();
      }
      /**
       * <code>optional bool check_mask = 6;</code>
       */
      public boolean getCheckMask() {
        return instance.getCheckMask();
      }
      /**
       * <code>optional bool check_mask = 6;</code>
       */
      public Builder setCheckMask(boolean value) {
        copyOnWrite();
        instance.setCheckMask(value);
        return this;
      }
      /**
       * <code>optional bool check_mask = 6;</code>
       */
      public Builder clearCheckMask() {
        copyOnWrite();
        instance.clearCheckMask();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.RoomMsgNotice)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasVersion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasSenderId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasRoomName()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasNoticeProperty()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice other = (YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice) arg1;
          version_ = visitor.visitInt(
              hasVersion(), version_,
              other.hasVersion(), other.version_);
          senderId_ = visitor.visitByteString(
              hasSenderId(), senderId_,
              other.hasSenderId(), other.senderId_);
          roomName_ = visitor.visitByteString(
              hasRoomName(), roomName_,
              other.hasRoomName(), other.roomName_);
          noticeProperty_ = visitor.visitInt(
              hasNoticeProperty(), noticeProperty_,
              other.hasNoticeProperty(), other.noticeProperty_);
          msgContent_ = visitor.visitByteString(
              hasMsgContent(), msgContent_,
              other.hasMsgContent(), other.msgContent_);
          checkMask_ = visitor.visitBoolean(
              hasCheckMask(), checkMask_,
              other.hasCheckMask(), other.checkMask_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  version_ = input.readInt32();
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000002;
                  senderId_ = input.readBytes();
                  break;
                }
                case 26: {
                  bitField0_ |= 0x00000004;
                  roomName_ = input.readBytes();
                  break;
                }
                case 32: {
                  bitField0_ |= 0x00000008;
                  noticeProperty_ = input.readInt32();
                  break;
                }
                case 42: {
                  bitField0_ |= 0x00000010;
                  msgContent_ = input.readBytes();
                  break;
                }
                case 48: {
                  bitField0_ |= 0x00000020;
                  checkMask_ = input.readBool();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.RoomMsgNotice)
    private static final YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RoomMsgNotice();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeSndmsg.RoomMsgNotice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RoomMsgNotice> PARSER;

    public static com.google.protobuf.Parser<RoomMsgNotice> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
