// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logout_svr/youme_logout.proto

package YOUMEServiceProtocol;

public final class YoumeLogout {
  private YoumeLogout() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LogoutReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.LogoutReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();
  }
  /**
   * <pre>
   * 登出请求包体
   * </pre>
   *
   * Protobuf type {@code YOUMEServiceProtocol.LogoutReq}
   */
  public  static final class LogoutReq extends
      com.google.protobuf.GeneratedMessageLite<
          LogoutReq, LogoutReq.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.LogoutReq)
      LogoutReqOrBuilder {
    private LogoutReq() {
    }
    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeLogout.LogoutReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeLogout.LogoutReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 登出请求包体
     * </pre>
     *
     * Protobuf type {@code YOUMEServiceProtocol.LogoutReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeLogout.LogoutReq, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.LogoutReq)
        YOUMEServiceProtocol.YoumeLogout.LogoutReqOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeLogout.LogoutReq.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.LogoutReq)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeLogout.LogoutReq();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasVersion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeLogout.LogoutReq other = (YOUMEServiceProtocol.YoumeLogout.LogoutReq) arg1;
          version_ = visitor.visitInt(
              hasVersion(), version_,
              other.hasVersion(), other.version_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  version_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeLogout.LogoutReq.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.LogoutReq)
    private static final YOUMEServiceProtocol.YoumeLogout.LogoutReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LogoutReq();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeLogout.LogoutReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LogoutReq> PARSER;

    public static com.google.protobuf.Parser<LogoutReq> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LogoutRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.LogoutRsp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    boolean hasRet();
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    int getRet();
  }
  /**
   * <pre>
   * 登出应答包体
   * </pre>
   *
   * Protobuf type {@code YOUMEServiceProtocol.LogoutRsp}
   */
  public  static final class LogoutRsp extends
      com.google.protobuf.GeneratedMessageLite<
          LogoutRsp, LogoutRsp.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.LogoutRsp)
      LogoutRspOrBuilder {
    private LogoutRsp() {
    }
    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
    }

    public static final int RET_FIELD_NUMBER = 2;
    private int ret_;
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    public int getRet() {
      return ret_;
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    private void setRet(int value) {
      bitField0_ |= 0x00000002;
      ret_ = value;
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    private void clearRet() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ret_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ret_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ret_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeLogout.LogoutRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeLogout.LogoutRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeLogout.LogoutRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 登出应答包体
     * </pre>
     *
     * Protobuf type {@code YOUMEServiceProtocol.LogoutRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeLogout.LogoutRsp, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.LogoutRsp)
        YOUMEServiceProtocol.YoumeLogout.LogoutRspOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeLogout.LogoutRsp.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public boolean hasRet() {
        return instance.hasRet();
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public int getRet() {
        return instance.getRet();
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public Builder setRet(int value) {
        copyOnWrite();
        instance.setRet(value);
        return this;
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public Builder clearRet() {
        copyOnWrite();
        instance.clearRet();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.LogoutRsp)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeLogout.LogoutRsp();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasVersion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasRet()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeLogout.LogoutRsp other = (YOUMEServiceProtocol.YoumeLogout.LogoutRsp) arg1;
          version_ = visitor.visitInt(
              hasVersion(), version_,
              other.hasVersion(), other.version_);
          ret_ = visitor.visitInt(
              hasRet(), ret_,
              other.hasRet(), other.ret_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  version_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  ret_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeLogout.LogoutRsp.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.LogoutRsp)
    private static final YOUMEServiceProtocol.YoumeLogout.LogoutRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LogoutRsp();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeLogout.LogoutRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LogoutRsp> PARSER;

    public static com.google.protobuf.Parser<LogoutRsp> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
