// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_svr/youme_login.proto

package YOUMEServiceProtocol;

public final class YoumeLogin {
  private YoumeLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LoginReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.LoginReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>required string device_token = 2;</code>
     */
    boolean hasDeviceToken();
    /**
     * <code>required string device_token = 2;</code>
     */
    java.lang.String getDeviceToken();
    /**
     * <code>required string device_token = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceTokenBytes();

    /**
     * <code>required string pswd = 3;</code>
     */
    boolean hasPswd();
    /**
     * <code>required string pswd = 3;</code>
     */
    java.lang.String getPswd();
    /**
     * <code>required string pswd = 3;</code>
     */
    com.google.protobuf.ByteString
        getPswdBytes();

    /**
     * <code>required int32 os_type = 4;</code>
     */
    boolean hasOsType();
    /**
     * <code>required int32 os_type = 4;</code>
     */
    int getOsType();

    /**
     * <code>optional string auth_token = 5;</code>
     */
    boolean hasAuthToken();
    /**
     * <code>optional string auth_token = 5;</code>
     */
    java.lang.String getAuthToken();
    /**
     * <code>optional string auth_token = 5;</code>
     */
    com.google.protobuf.ByteString
        getAuthTokenBytes();

    /**
     * <code>optional string user_info = 6;</code>
     */
    boolean hasUserInfo();
    /**
     * <code>optional string user_info = 6;</code>
     */
    java.lang.String getUserInfo();
    /**
     * <code>optional string user_info = 6;</code>
     */
    com.google.protobuf.ByteString
        getUserInfoBytes();
  }
  /**
   * <pre>
   * 登录请求包体, 用接入包头加密 
   * </pre>
   *
   * Protobuf type {@code YOUMEServiceProtocol.LoginReq}
   */
  public  static final class LoginReq extends
      com.google.protobuf.GeneratedMessageLite<
          LoginReq, LoginReq.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.LoginReq)
      LoginReqOrBuilder {
    private LoginReq() {
      deviceToken_ = "";
      pswd_ = "";
      authToken_ = "";
      userInfo_ = "";
    }
    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
    }

    public static final int DEVICE_TOKEN_FIELD_NUMBER = 2;
    private java.lang.String deviceToken_;
    /**
     * <code>required string device_token = 2;</code>
     */
    public boolean hasDeviceToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string device_token = 2;</code>
     */
    public java.lang.String getDeviceToken() {
      return deviceToken_;
    }
    /**
     * <code>required string device_token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTokenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceToken_);
    }
    /**
     * <code>required string device_token = 2;</code>
     */
    private void setDeviceToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      deviceToken_ = value;
    }
    /**
     * <code>required string device_token = 2;</code>
     */
    private void clearDeviceToken() {
      bitField0_ = (bitField0_ & ~0x00000002);
      deviceToken_ = getDefaultInstance().getDeviceToken();
    }
    /**
     * <code>required string device_token = 2;</code>
     */
    private void setDeviceTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      deviceToken_ = value.toStringUtf8();
    }

    public static final int PSWD_FIELD_NUMBER = 3;
    private java.lang.String pswd_;
    /**
     * <code>required string pswd = 3;</code>
     */
    public boolean hasPswd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string pswd = 3;</code>
     */
    public java.lang.String getPswd() {
      return pswd_;
    }
    /**
     * <code>required string pswd = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPswdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pswd_);
    }
    /**
     * <code>required string pswd = 3;</code>
     */
    private void setPswd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      pswd_ = value;
    }
    /**
     * <code>required string pswd = 3;</code>
     */
    private void clearPswd() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pswd_ = getDefaultInstance().getPswd();
    }
    /**
     * <code>required string pswd = 3;</code>
     */
    private void setPswdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      pswd_ = value.toStringUtf8();
    }

    public static final int OS_TYPE_FIELD_NUMBER = 4;
    private int osType_;
    /**
     * <code>required int32 os_type = 4;</code>
     */
    public boolean hasOsType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 os_type = 4;</code>
     */
    public int getOsType() {
      return osType_;
    }
    /**
     * <code>required int32 os_type = 4;</code>
     */
    private void setOsType(int value) {
      bitField0_ |= 0x00000008;
      osType_ = value;
    }
    /**
     * <code>required int32 os_type = 4;</code>
     */
    private void clearOsType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      osType_ = 0;
    }

    public static final int AUTH_TOKEN_FIELD_NUMBER = 5;
    private java.lang.String authToken_;
    /**
     * <code>optional string auth_token = 5;</code>
     */
    public boolean hasAuthToken() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string auth_token = 5;</code>
     */
    public java.lang.String getAuthToken() {
      return authToken_;
    }
    /**
     * <code>optional string auth_token = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAuthTokenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(authToken_);
    }
    /**
     * <code>optional string auth_token = 5;</code>
     */
    private void setAuthToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      authToken_ = value;
    }
    /**
     * <code>optional string auth_token = 5;</code>
     */
    private void clearAuthToken() {
      bitField0_ = (bitField0_ & ~0x00000010);
      authToken_ = getDefaultInstance().getAuthToken();
    }
    /**
     * <code>optional string auth_token = 5;</code>
     */
    private void setAuthTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      authToken_ = value.toStringUtf8();
    }

    public static final int USER_INFO_FIELD_NUMBER = 6;
    private java.lang.String userInfo_;
    /**
     * <code>optional string user_info = 6;</code>
     */
    public boolean hasUserInfo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string user_info = 6;</code>
     */
    public java.lang.String getUserInfo() {
      return userInfo_;
    }
    /**
     * <code>optional string user_info = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUserInfoBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userInfo_);
    }
    /**
     * <code>optional string user_info = 6;</code>
     */
    private void setUserInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      userInfo_ = value;
    }
    /**
     * <code>optional string user_info = 6;</code>
     */
    private void clearUserInfo() {
      bitField0_ = (bitField0_ & ~0x00000020);
      userInfo_ = getDefaultInstance().getUserInfo();
    }
    /**
     * <code>optional string user_info = 6;</code>
     */
    private void setUserInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      userInfo_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getDeviceToken());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeString(3, getPswd());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, osType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeString(5, getAuthToken());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeString(6, getUserInfo());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDeviceToken());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getPswd());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, osType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getAuthToken());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getUserInfo());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeLogin.LoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeLogin.LoginReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 登录请求包体, 用接入包头加密 
     * </pre>
     *
     * Protobuf type {@code YOUMEServiceProtocol.LoginReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeLogin.LoginReq, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.LoginReq)
        YOUMEServiceProtocol.YoumeLogin.LoginReqOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeLogin.LoginReq.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       * <code>required string device_token = 2;</code>
       */
      public boolean hasDeviceToken() {
        return instance.hasDeviceToken();
      }
      /**
       * <code>required string device_token = 2;</code>
       */
      public java.lang.String getDeviceToken() {
        return instance.getDeviceToken();
      }
      /**
       * <code>required string device_token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceTokenBytes() {
        return instance.getDeviceTokenBytes();
      }
      /**
       * <code>required string device_token = 2;</code>
       */
      public Builder setDeviceToken(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeviceToken(value);
        return this;
      }
      /**
       * <code>required string device_token = 2;</code>
       */
      public Builder clearDeviceToken() {
        copyOnWrite();
        instance.clearDeviceToken();
        return this;
      }
      /**
       * <code>required string device_token = 2;</code>
       */
      public Builder setDeviceTokenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceTokenBytes(value);
        return this;
      }

      /**
       * <code>required string pswd = 3;</code>
       */
      public boolean hasPswd() {
        return instance.hasPswd();
      }
      /**
       * <code>required string pswd = 3;</code>
       */
      public java.lang.String getPswd() {
        return instance.getPswd();
      }
      /**
       * <code>required string pswd = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPswdBytes() {
        return instance.getPswdBytes();
      }
      /**
       * <code>required string pswd = 3;</code>
       */
      public Builder setPswd(
          java.lang.String value) {
        copyOnWrite();
        instance.setPswd(value);
        return this;
      }
      /**
       * <code>required string pswd = 3;</code>
       */
      public Builder clearPswd() {
        copyOnWrite();
        instance.clearPswd();
        return this;
      }
      /**
       * <code>required string pswd = 3;</code>
       */
      public Builder setPswdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPswdBytes(value);
        return this;
      }

      /**
       * <code>required int32 os_type = 4;</code>
       */
      public boolean hasOsType() {
        return instance.hasOsType();
      }
      /**
       * <code>required int32 os_type = 4;</code>
       */
      public int getOsType() {
        return instance.getOsType();
      }
      /**
       * <code>required int32 os_type = 4;</code>
       */
      public Builder setOsType(int value) {
        copyOnWrite();
        instance.setOsType(value);
        return this;
      }
      /**
       * <code>required int32 os_type = 4;</code>
       */
      public Builder clearOsType() {
        copyOnWrite();
        instance.clearOsType();
        return this;
      }

      /**
       * <code>optional string auth_token = 5;</code>
       */
      public boolean hasAuthToken() {
        return instance.hasAuthToken();
      }
      /**
       * <code>optional string auth_token = 5;</code>
       */
      public java.lang.String getAuthToken() {
        return instance.getAuthToken();
      }
      /**
       * <code>optional string auth_token = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAuthTokenBytes() {
        return instance.getAuthTokenBytes();
      }
      /**
       * <code>optional string auth_token = 5;</code>
       */
      public Builder setAuthToken(
          java.lang.String value) {
        copyOnWrite();
        instance.setAuthToken(value);
        return this;
      }
      /**
       * <code>optional string auth_token = 5;</code>
       */
      public Builder clearAuthToken() {
        copyOnWrite();
        instance.clearAuthToken();
        return this;
      }
      /**
       * <code>optional string auth_token = 5;</code>
       */
      public Builder setAuthTokenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAuthTokenBytes(value);
        return this;
      }

      /**
       * <code>optional string user_info = 6;</code>
       */
      public boolean hasUserInfo() {
        return instance.hasUserInfo();
      }
      /**
       * <code>optional string user_info = 6;</code>
       */
      public java.lang.String getUserInfo() {
        return instance.getUserInfo();
      }
      /**
       * <code>optional string user_info = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUserInfoBytes() {
        return instance.getUserInfoBytes();
      }
      /**
       * <code>optional string user_info = 6;</code>
       */
      public Builder setUserInfo(
          java.lang.String value) {
        copyOnWrite();
        instance.setUserInfo(value);
        return this;
      }
      /**
       * <code>optional string user_info = 6;</code>
       */
      public Builder clearUserInfo() {
        copyOnWrite();
        instance.clearUserInfo();
        return this;
      }
      /**
       * <code>optional string user_info = 6;</code>
       */
      public Builder setUserInfoBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserInfoBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.LoginReq)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeLogin.LoginReq();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasVersion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasDeviceToken()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasPswd()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasOsType()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeLogin.LoginReq other = (YOUMEServiceProtocol.YoumeLogin.LoginReq) arg1;
          version_ = visitor.visitInt(
              hasVersion(), version_,
              other.hasVersion(), other.version_);
          deviceToken_ = visitor.visitString(
              hasDeviceToken(), deviceToken_,
              other.hasDeviceToken(), other.deviceToken_);
          pswd_ = visitor.visitString(
              hasPswd(), pswd_,
              other.hasPswd(), other.pswd_);
          osType_ = visitor.visitInt(
              hasOsType(), osType_,
              other.hasOsType(), other.osType_);
          authToken_ = visitor.visitString(
              hasAuthToken(), authToken_,
              other.hasAuthToken(), other.authToken_);
          userInfo_ = visitor.visitString(
              hasUserInfo(), userInfo_,
              other.hasUserInfo(), other.userInfo_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  version_ = input.readInt32();
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  deviceToken_ = s;
                  break;
                }
                case 26: {
                  String s = input.readString();
                  bitField0_ |= 0x00000004;
                  pswd_ = s;
                  break;
                }
                case 32: {
                  bitField0_ |= 0x00000008;
                  osType_ = input.readInt32();
                  break;
                }
                case 42: {
                  String s = input.readString();
                  bitField0_ |= 0x00000010;
                  authToken_ = s;
                  break;
                }
                case 50: {
                  String s = input.readString();
                  bitField0_ |= 0x00000020;
                  userInfo_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeLogin.LoginReq.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.LoginReq)
    private static final YOUMEServiceProtocol.YoumeLogin.LoginReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginReq();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeLogin.LoginReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LoginReq> PARSER;

    public static com.google.protobuf.Parser<LoginReq> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LoginRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YOUMEServiceProtocol.LoginRsp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    boolean hasRet();
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    int getRet();

    /**
     * <pre>
     * 后续通讯的加密 key
     * </pre>
     *
     * <code>required string secret = 3;</code>
     */
    boolean hasSecret();
    /**
     * <pre>
     * 后续通讯的加密 key
     * </pre>
     *
     * <code>required string secret = 3;</code>
     */
    java.lang.String getSecret();
    /**
     * <pre>
     * 后续通讯的加密 key
     * </pre>
     *
     * <code>required string secret = 3;</code>
     */
    com.google.protobuf.ByteString
        getSecretBytes();

    /**
     * <code>optional string ret_msg = 4;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>optional string ret_msg = 4;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string ret_msg = 4;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();
  }
  /**
   * <pre>
   * 登录应答包体, 用接入包头加密
   * </pre>
   *
   * Protobuf type {@code YOUMEServiceProtocol.LoginRsp}
   */
  public  static final class LoginRsp extends
      com.google.protobuf.GeneratedMessageLite<
          LoginRsp, LoginRsp.Builder> implements
      // @@protoc_insertion_point(message_implements:YOUMEServiceProtocol.LoginRsp)
      LoginRspOrBuilder {
    private LoginRsp() {
      secret_ = "";
      retMsg_ = "";
    }
    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
    }

    public static final int RET_FIELD_NUMBER = 2;
    private int ret_;
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    public int getRet() {
      return ret_;
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    private void setRet(int value) {
      bitField0_ |= 0x00000002;
      ret_ = value;
    }
    /**
     * <pre>
     * 返回码, 0成功, 其他失败
     * </pre>
     *
     * <code>required int32 ret = 2;</code>
     */
    private void clearRet() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ret_ = 0;
    }

    public static final int SECRET_FIELD_NUMBER = 3;
    private java.lang.String secret_;
    /**
     * <pre>
     * 后续通讯的加密 key
     * </pre>
     *
     * <code>required string secret = 3;</code>
     */
    public boolean hasSecret() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 后续通讯的加密 key
     * </pre>
     *
     * <code>required string secret = 3;</code>
     */
    public java.lang.String getSecret() {
      return secret_;
    }
    /**
     * <pre>
     * 后续通讯的加密 key
     * </pre>
     *
     * <code>required string secret = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(secret_);
    }
    /**
     * <pre>
     * 后续通讯的加密 key
     * </pre>
     *
     * <code>required string secret = 3;</code>
     */
    private void setSecret(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      secret_ = value;
    }
    /**
     * <pre>
     * 后续通讯的加密 key
     * </pre>
     *
     * <code>required string secret = 3;</code>
     */
    private void clearSecret() {
      bitField0_ = (bitField0_ & ~0x00000004);
      secret_ = getDefaultInstance().getSecret();
    }
    /**
     * <pre>
     * 后续通讯的加密 key
     * </pre>
     *
     * <code>required string secret = 3;</code>
     */
    private void setSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      secret_ = value.toStringUtf8();
    }

    public static final int RET_MSG_FIELD_NUMBER = 4;
    private java.lang.String retMsg_;
    /**
     * <code>optional string ret_msg = 4;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string ret_msg = 4;</code>
     */
    public java.lang.String getRetMsg() {
      return retMsg_;
    }
    /**
     * <code>optional string ret_msg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(retMsg_);
    }
    /**
     * <code>optional string ret_msg = 4;</code>
     */
    private void setRetMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      retMsg_ = value;
    }
    /**
     * <code>optional string ret_msg = 4;</code>
     */
    private void clearRetMsg() {
      bitField0_ = (bitField0_ & ~0x00000008);
      retMsg_ = getDefaultInstance().getRetMsg();
    }
    /**
     * <code>optional string ret_msg = 4;</code>
     */
    private void setRetMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      retMsg_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ret_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeString(3, getSecret());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeString(4, getRetMsg());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ret_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getSecret());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getRetMsg());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static YOUMEServiceProtocol.YoumeLogin.LoginRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static YOUMEServiceProtocol.YoumeLogin.LoginRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(YOUMEServiceProtocol.YoumeLogin.LoginRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 登录应答包体, 用接入包头加密
     * </pre>
     *
     * Protobuf type {@code YOUMEServiceProtocol.LoginRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          YOUMEServiceProtocol.YoumeLogin.LoginRsp, Builder> implements
        // @@protoc_insertion_point(builder_implements:YOUMEServiceProtocol.LoginRsp)
        YOUMEServiceProtocol.YoumeLogin.LoginRspOrBuilder {
      // Construct using YOUMEServiceProtocol.YoumeLogin.LoginRsp.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return instance.hasVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public boolean hasRet() {
        return instance.hasRet();
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public int getRet() {
        return instance.getRet();
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public Builder setRet(int value) {
        copyOnWrite();
        instance.setRet(value);
        return this;
      }
      /**
       * <pre>
       * 返回码, 0成功, 其他失败
       * </pre>
       *
       * <code>required int32 ret = 2;</code>
       */
      public Builder clearRet() {
        copyOnWrite();
        instance.clearRet();
        return this;
      }

      /**
       * <pre>
       * 后续通讯的加密 key
       * </pre>
       *
       * <code>required string secret = 3;</code>
       */
      public boolean hasSecret() {
        return instance.hasSecret();
      }
      /**
       * <pre>
       * 后续通讯的加密 key
       * </pre>
       *
       * <code>required string secret = 3;</code>
       */
      public java.lang.String getSecret() {
        return instance.getSecret();
      }
      /**
       * <pre>
       * 后续通讯的加密 key
       * </pre>
       *
       * <code>required string secret = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSecretBytes() {
        return instance.getSecretBytes();
      }
      /**
       * <pre>
       * 后续通讯的加密 key
       * </pre>
       *
       * <code>required string secret = 3;</code>
       */
      public Builder setSecret(
          java.lang.String value) {
        copyOnWrite();
        instance.setSecret(value);
        return this;
      }
      /**
       * <pre>
       * 后续通讯的加密 key
       * </pre>
       *
       * <code>required string secret = 3;</code>
       */
      public Builder clearSecret() {
        copyOnWrite();
        instance.clearSecret();
        return this;
      }
      /**
       * <pre>
       * 后续通讯的加密 key
       * </pre>
       *
       * <code>required string secret = 3;</code>
       */
      public Builder setSecretBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSecretBytes(value);
        return this;
      }

      /**
       * <code>optional string ret_msg = 4;</code>
       */
      public boolean hasRetMsg() {
        return instance.hasRetMsg();
      }
      /**
       * <code>optional string ret_msg = 4;</code>
       */
      public java.lang.String getRetMsg() {
        return instance.getRetMsg();
      }
      /**
       * <code>optional string ret_msg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        return instance.getRetMsgBytes();
      }
      /**
       * <code>optional string ret_msg = 4;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        copyOnWrite();
        instance.setRetMsg(value);
        return this;
      }
      /**
       * <code>optional string ret_msg = 4;</code>
       */
      public Builder clearRetMsg() {
        copyOnWrite();
        instance.clearRetMsg();
        return this;
      }
      /**
       * <code>optional string ret_msg = 4;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRetMsgBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:YOUMEServiceProtocol.LoginRsp)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new YOUMEServiceProtocol.YoumeLogin.LoginRsp();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasVersion()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasRet()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasSecret()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          YOUMEServiceProtocol.YoumeLogin.LoginRsp other = (YOUMEServiceProtocol.YoumeLogin.LoginRsp) arg1;
          version_ = visitor.visitInt(
              hasVersion(), version_,
              other.hasVersion(), other.version_);
          ret_ = visitor.visitInt(
              hasRet(), ret_,
              other.hasRet(), other.ret_);
          secret_ = visitor.visitString(
              hasSecret(), secret_,
              other.hasSecret(), other.secret_);
          retMsg_ = visitor.visitString(
              hasRetMsg(), retMsg_,
              other.hasRetMsg(), other.retMsg_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  version_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  ret_ = input.readInt32();
                  break;
                }
                case 26: {
                  String s = input.readString();
                  bitField0_ |= 0x00000004;
                  secret_ = s;
                  break;
                }
                case 34: {
                  String s = input.readString();
                  bitField0_ |= 0x00000008;
                  retMsg_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (YOUMEServiceProtocol.YoumeLogin.LoginRsp.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.LoginRsp)
    private static final YOUMEServiceProtocol.YoumeLogin.LoginRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginRsp();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static YOUMEServiceProtocol.YoumeLogin.LoginRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LoginRsp> PARSER;

    public static com.google.protobuf.Parser<LoginRsp> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
