/*
 * Automatically generated header file: don't edit
 */
/*
#define HAVE_DOT_CONFIG 1
#undef CONFIG_PLATFORM_LINUX
#define CONFIG_PLATFORM_CYGWIN 1
#undef CONFIG_PLATFORM_WIN32
*/
/*
 * General Configuration
 */
#define PREFIX "/usr/local"

namespace youmecommon
{
#undef CONFIG_DEBUG
#define CONFIG_STRIP_UNWANTED_SECTIONS 1
#undef CONFIG_VISUAL_STUDIO_7_0
#undef CONFIG_VISUAL_STUDIO_8_0
#undef CONFIG_VISUAL_STUDIO_10_0
#define CONFIG_VISUAL_STUDIO_7_0_BASE ""
#define CONFIG_VISUAL_STUDIO_8_0_BASE ""
#define CONFIG_VISUAL_STUDIO_10_0_BASE ""
#define CONFIG_EXTRA_CFLAGS_OPTIONS ""
#define CONFIG_EXTRA_LDFLAGS_OPTIONS ""

	/*
	 * SSL Library
	 */
#undef CONFIG_SSL_SERVER_ONLY
#undef CONFIG_SSL_CERT_VERIFICATION
#undef CONFIG_SSL_ENABLE_CLIENT
#define CONFIG_SSL_FULL_MODE 1
#undef CONFIG_SSL_SKELETON_MODE
#undef CONFIG_SSL_PROT_LOW
#define CONFIG_SSL_PROT_MEDIUM 1
#undef CONFIG_SSL_PROT_HIGH
#define CONFIG_SSL_USE_DEFAULT_KEY 1
#define CONFIG_SSL_PRIVATE_KEY_LOCATION ""
#define CONFIG_SSL_PRIVATE_KEY_PASSWORD ""
#define CONFIG_SSL_X509_CERT_LOCATION ""
#undef CONFIG_SSL_GENERATE_X509_CERT
#define CONFIG_SSL_X509_COMMON_NAME ""
#define CONFIG_SSL_X509_ORGANIZATION_NAME ""
#define CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME ""
#define CONFIG_SSL_HAS_PEM 1
#define CONFIG_SSL_USE_PKCS12 1
#define CONFIG_SSL_EXPIRY_TIME 24
#define CONFIG_X509_MAX_CA_CERTS 150
#define CONFIG_SSL_MAX_CERTS 3
#undef CONFIG_SSL_CTX_MUTEXING
#undef CONFIG_PERFORMANCE_TESTING
#undef CONFIG_SSL_TEST
#undef CONFIG_AXTLSWRAP
#define CONFIG_AXHTTPD 1


	/*
	 * BigInt Options

	 #undef CONFIG_BIGINT_CLASSICAL
	 #undef CONFIG_BIGINT_MONTGOMERY
	 #define CONFIG_BIGINT_BARRETT 1
	 #define CONFIG_BIGINT_CRT 1
	 #undef CONFIG_BIGINT_KARATSUBA
	 #define MUL_KARATSUBA_THRESH
	 #define SQU_KARATSUBA_THRESH
	 #define CONFIG_BIGINT_SLIDING_WINDOW 1
	 #define CONFIG_BIGINT_SQUARE 1
	 #undef CONFIG_BIGINT_CHECK_ON
	 #define CONFIG_INTEGER_32BIT 1
	 #undef CONFIG_INTEGER_16BIT
	 #undef CONFIG_INTEGER_8BIT
	 */
}