# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mask_usermsg_svr/youme_mask_usermsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mask_usermsg_svr/youme_mask_usermsg.proto',
  package='YOUMEServiceProtocol',
  syntax='proto2',
  serialized_pb=_b('\n)mask_usermsg_svr/youme_mask_usermsg.proto\x12\x14YOUMEServiceProtocol\"a\n\x11SetMaskMsgUserReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0f\n\x07room_id\x18\x02 \x02(\x0c\x12\x12\n\nmask_right\x18\x03 \x02(\x05\x12\x16\n\x0emask_user_list\x18\x04 \x03(\x0c\"1\n\x11SetMaskMsgUserRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\"q\n\x11GetMaskMsgUserReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0f\n\x07room_id\x18\x02 \x02(\x0c\x12\x12\n\nmask_right\x18\x03 \x02(\x05\x12\x10\n\x08mask_seq\x18\x04 \x02(\x04\x12\x14\n\x0cnumber_limit\x18\x05 \x01(\r\"m\n\x11GetMaskMsgUserRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\x12\x10\n\x08user_cnt\x18\x03 \x02(\r\x12\x10\n\x08mask_seq\x18\x04 \x02(\x04\x12\x16\n\x0emask_user_list\x18\x05 \x03(\x0c\"7\n\x13\x43leanMaskMsgUserReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0f\n\x07room_id\x18\x02 \x02(\x0c\"3\n\x13\x43leanMaskMsgUserRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\x42\x02H\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SETMASKMSGUSERREQ = _descriptor.Descriptor(
  name='SetMaskMsgUserReq',
  full_name='YOUMEServiceProtocol.SetMaskMsgUserReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.SetMaskMsgUserReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='YOUMEServiceProtocol.SetMaskMsgUserReq.room_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mask_right', full_name='YOUMEServiceProtocol.SetMaskMsgUserReq.mask_right', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mask_user_list', full_name='YOUMEServiceProtocol.SetMaskMsgUserReq.mask_user_list', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=164,
)


_SETMASKMSGUSERRSP = _descriptor.Descriptor(
  name='SetMaskMsgUserRsp',
  full_name='YOUMEServiceProtocol.SetMaskMsgUserRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.SetMaskMsgUserRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.SetMaskMsgUserRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=215,
)


_GETMASKMSGUSERREQ = _descriptor.Descriptor(
  name='GetMaskMsgUserReq',
  full_name='YOUMEServiceProtocol.GetMaskMsgUserReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.GetMaskMsgUserReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='YOUMEServiceProtocol.GetMaskMsgUserReq.room_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mask_right', full_name='YOUMEServiceProtocol.GetMaskMsgUserReq.mask_right', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mask_seq', full_name='YOUMEServiceProtocol.GetMaskMsgUserReq.mask_seq', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number_limit', full_name='YOUMEServiceProtocol.GetMaskMsgUserReq.number_limit', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=330,
)


_GETMASKMSGUSERRSP = _descriptor.Descriptor(
  name='GetMaskMsgUserRsp',
  full_name='YOUMEServiceProtocol.GetMaskMsgUserRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.GetMaskMsgUserRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.GetMaskMsgUserRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_cnt', full_name='YOUMEServiceProtocol.GetMaskMsgUserRsp.user_cnt', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mask_seq', full_name='YOUMEServiceProtocol.GetMaskMsgUserRsp.mask_seq', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mask_user_list', full_name='YOUMEServiceProtocol.GetMaskMsgUserRsp.mask_user_list', index=4,
      number=5, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=441,
)


_CLEANMASKMSGUSERREQ = _descriptor.Descriptor(
  name='CleanMaskMsgUserReq',
  full_name='YOUMEServiceProtocol.CleanMaskMsgUserReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.CleanMaskMsgUserReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='YOUMEServiceProtocol.CleanMaskMsgUserReq.room_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=498,
)


_CLEANMASKMSGUSERRSP = _descriptor.Descriptor(
  name='CleanMaskMsgUserRsp',
  full_name='YOUMEServiceProtocol.CleanMaskMsgUserRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.CleanMaskMsgUserRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.CleanMaskMsgUserRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=551,
)

DESCRIPTOR.message_types_by_name['SetMaskMsgUserReq'] = _SETMASKMSGUSERREQ
DESCRIPTOR.message_types_by_name['SetMaskMsgUserRsp'] = _SETMASKMSGUSERRSP
DESCRIPTOR.message_types_by_name['GetMaskMsgUserReq'] = _GETMASKMSGUSERREQ
DESCRIPTOR.message_types_by_name['GetMaskMsgUserRsp'] = _GETMASKMSGUSERRSP
DESCRIPTOR.message_types_by_name['CleanMaskMsgUserReq'] = _CLEANMASKMSGUSERREQ
DESCRIPTOR.message_types_by_name['CleanMaskMsgUserRsp'] = _CLEANMASKMSGUSERRSP

SetMaskMsgUserReq = _reflection.GeneratedProtocolMessageType('SetMaskMsgUserReq', (_message.Message,), dict(
  DESCRIPTOR = _SETMASKMSGUSERREQ,
  __module__ = 'mask_usermsg_svr.youme_mask_usermsg_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.SetMaskMsgUserReq)
  ))
_sym_db.RegisterMessage(SetMaskMsgUserReq)

SetMaskMsgUserRsp = _reflection.GeneratedProtocolMessageType('SetMaskMsgUserRsp', (_message.Message,), dict(
  DESCRIPTOR = _SETMASKMSGUSERRSP,
  __module__ = 'mask_usermsg_svr.youme_mask_usermsg_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.SetMaskMsgUserRsp)
  ))
_sym_db.RegisterMessage(SetMaskMsgUserRsp)

GetMaskMsgUserReq = _reflection.GeneratedProtocolMessageType('GetMaskMsgUserReq', (_message.Message,), dict(
  DESCRIPTOR = _GETMASKMSGUSERREQ,
  __module__ = 'mask_usermsg_svr.youme_mask_usermsg_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetMaskMsgUserReq)
  ))
_sym_db.RegisterMessage(GetMaskMsgUserReq)

GetMaskMsgUserRsp = _reflection.GeneratedProtocolMessageType('GetMaskMsgUserRsp', (_message.Message,), dict(
  DESCRIPTOR = _GETMASKMSGUSERRSP,
  __module__ = 'mask_usermsg_svr.youme_mask_usermsg_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetMaskMsgUserRsp)
  ))
_sym_db.RegisterMessage(GetMaskMsgUserRsp)

CleanMaskMsgUserReq = _reflection.GeneratedProtocolMessageType('CleanMaskMsgUserReq', (_message.Message,), dict(
  DESCRIPTOR = _CLEANMASKMSGUSERREQ,
  __module__ = 'mask_usermsg_svr.youme_mask_usermsg_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.CleanMaskMsgUserReq)
  ))
_sym_db.RegisterMessage(CleanMaskMsgUserReq)

CleanMaskMsgUserRsp = _reflection.GeneratedProtocolMessageType('CleanMaskMsgUserRsp', (_message.Message,), dict(
  DESCRIPTOR = _CLEANMASKMSGUSERRSP,
  __module__ = 'mask_usermsg_svr.youme_mask_usermsg_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.CleanMaskMsgUserRsp)
  ))
_sym_db.RegisterMessage(CleanMaskMsgUserRsp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
