# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userinfo_svr/youme_userinfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='userinfo_svr/youme_userinfo.proto',
  package='YOUMEServiceProtocol',
  syntax='proto2',
  serialized_pb=_b('\n!userinfo_svr/youme_userinfo.proto\x12\x14YOUMEServiceProtocol\"2\n\x0eGetUserInfoReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0f\n\x07user_id\x18\x02 \x02(\x0c\"Y\n\x0eGetUserInfoRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x11\n\tuser_info\x18\x02 \x02(\x0c\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x10\n\x08latitude\x18\x04 \x01(\x01\"7\n\x11UpdateUserInfoReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x11\n\tuser_info\x18\x02 \x02(\x0c\"1\n\x11UpdateUserInfoRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\x42\x02H\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETUSERINFOREQ = _descriptor.Descriptor(
  name='GetUserInfoReq',
  full_name='YOUMEServiceProtocol.GetUserInfoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.GetUserInfoReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='YOUMEServiceProtocol.GetUserInfoReq.user_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=109,
)


_GETUSERINFORSP = _descriptor.Descriptor(
  name='GetUserInfoRsp',
  full_name='YOUMEServiceProtocol.GetUserInfoRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.GetUserInfoRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_info', full_name='YOUMEServiceProtocol.GetUserInfoRsp.user_info', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='YOUMEServiceProtocol.GetUserInfoRsp.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='YOUMEServiceProtocol.GetUserInfoRsp.latitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=200,
)


_UPDATEUSERINFOREQ = _descriptor.Descriptor(
  name='UpdateUserInfoReq',
  full_name='YOUMEServiceProtocol.UpdateUserInfoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.UpdateUserInfoReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_info', full_name='YOUMEServiceProtocol.UpdateUserInfoReq.user_info', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=257,
)


_UPDATEUSERINFORSP = _descriptor.Descriptor(
  name='UpdateUserInfoRsp',
  full_name='YOUMEServiceProtocol.UpdateUserInfoRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.UpdateUserInfoRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.UpdateUserInfoRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=308,
)

DESCRIPTOR.message_types_by_name['GetUserInfoReq'] = _GETUSERINFOREQ
DESCRIPTOR.message_types_by_name['GetUserInfoRsp'] = _GETUSERINFORSP
DESCRIPTOR.message_types_by_name['UpdateUserInfoReq'] = _UPDATEUSERINFOREQ
DESCRIPTOR.message_types_by_name['UpdateUserInfoRsp'] = _UPDATEUSERINFORSP

GetUserInfoReq = _reflection.GeneratedProtocolMessageType('GetUserInfoReq', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERINFOREQ,
  __module__ = 'userinfo_svr.youme_userinfo_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetUserInfoReq)
  ))
_sym_db.RegisterMessage(GetUserInfoReq)

GetUserInfoRsp = _reflection.GeneratedProtocolMessageType('GetUserInfoRsp', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERINFORSP,
  __module__ = 'userinfo_svr.youme_userinfo_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetUserInfoRsp)
  ))
_sym_db.RegisterMessage(GetUserInfoRsp)

UpdateUserInfoReq = _reflection.GeneratedProtocolMessageType('UpdateUserInfoReq', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEUSERINFOREQ,
  __module__ = 'userinfo_svr.youme_userinfo_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.UpdateUserInfoReq)
  ))
_sym_db.RegisterMessage(UpdateUserInfoReq)

UpdateUserInfoRsp = _reflection.GeneratedProtocolMessageType('UpdateUserInfoRsp', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEUSERINFORSP,
  __module__ = 'userinfo_svr.youme_userinfo_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.UpdateUserInfoRsp)
  ))
_sym_db.RegisterMessage(UpdateUserInfoRsp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
