# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member_status_svr/youme_member_status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='member_status_svr/youme_member_status.proto',
  package='YOUMEServiceProtocol',
  syntax='proto2',
  serialized_pb=_b('\n+member_status_svr/youme_member_status.proto\x12\x14YOUMEServiceProtocol\"9\n\x11YoumeMemberStatus\x12\x0f\n\x07user_id\x18\x01 \x02(\x0c\x12\x13\n\x0bstatus_info\x18\x02 \x02(\x0c\"k\n\x12SetMemberStatusReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0c\n\x04type\x18\x02 \x02(\r\x12\x0f\n\x07room_id\x18\x03 \x02(\x0c\x12\x13\n\x0bstatus_info\x18\x04 \x02(\x0c\x12\x10\n\x08\x63hecksum\x18\x05 \x01(\t\"2\n\x12SetMemberStatusRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\"D\n\x12GetMemberStatusReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0f\n\x07room_id\x18\x02 \x02(\x0c\x12\x0c\n\x04type\x18\x03 \x01(\r\"\x8c\x01\n\x12GetMemberStatusRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\x12\x0f\n\x07room_id\x18\x03 \x01(\x0c\x12\x39\n\x08mem_list\x18\x04 \x03(\x0b\x32\'.YOUMEServiceProtocol.YoumeMemberStatus\x12\x0c\n\x04type\x18\x05 \x01(\r\"6\n\x12\x44\x65lMemberStatusReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0f\n\x07room_id\x18\x02 \x02(\x0c\"2\n\x12\x44\x65lMemberStatusRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\"(\n\x15\x44\x65lAllMemberStatusReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\"5\n\x15\x44\x65lAllMemberStatusRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\x42\x02H\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_YOUMEMEMBERSTATUS = _descriptor.Descriptor(
  name='YoumeMemberStatus',
  full_name='YOUMEServiceProtocol.YoumeMemberStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='YOUMEServiceProtocol.YoumeMemberStatus.user_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_info', full_name='YOUMEServiceProtocol.YoumeMemberStatus.status_info', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=126,
)


_SETMEMBERSTATUSREQ = _descriptor.Descriptor(
  name='SetMemberStatusReq',
  full_name='YOUMEServiceProtocol.SetMemberStatusReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.SetMemberStatusReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='YOUMEServiceProtocol.SetMemberStatusReq.type', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='YOUMEServiceProtocol.SetMemberStatusReq.room_id', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_info', full_name='YOUMEServiceProtocol.SetMemberStatusReq.status_info', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='checksum', full_name='YOUMEServiceProtocol.SetMemberStatusReq.checksum', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=235,
)


_SETMEMBERSTATUSRSP = _descriptor.Descriptor(
  name='SetMemberStatusRsp',
  full_name='YOUMEServiceProtocol.SetMemberStatusRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.SetMemberStatusRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.SetMemberStatusRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=287,
)


_GETMEMBERSTATUSREQ = _descriptor.Descriptor(
  name='GetMemberStatusReq',
  full_name='YOUMEServiceProtocol.GetMemberStatusReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.GetMemberStatusReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='YOUMEServiceProtocol.GetMemberStatusReq.room_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='YOUMEServiceProtocol.GetMemberStatusReq.type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=357,
)


_GETMEMBERSTATUSRSP = _descriptor.Descriptor(
  name='GetMemberStatusRsp',
  full_name='YOUMEServiceProtocol.GetMemberStatusRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.GetMemberStatusRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.GetMemberStatusRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='YOUMEServiceProtocol.GetMemberStatusRsp.room_id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mem_list', full_name='YOUMEServiceProtocol.GetMemberStatusRsp.mem_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='YOUMEServiceProtocol.GetMemberStatusRsp.type', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=500,
)


_DELMEMBERSTATUSREQ = _descriptor.Descriptor(
  name='DelMemberStatusReq',
  full_name='YOUMEServiceProtocol.DelMemberStatusReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.DelMemberStatusReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='YOUMEServiceProtocol.DelMemberStatusReq.room_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=556,
)


_DELMEMBERSTATUSRSP = _descriptor.Descriptor(
  name='DelMemberStatusRsp',
  full_name='YOUMEServiceProtocol.DelMemberStatusRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.DelMemberStatusRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.DelMemberStatusRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=608,
)


_DELALLMEMBERSTATUSREQ = _descriptor.Descriptor(
  name='DelAllMemberStatusReq',
  full_name='YOUMEServiceProtocol.DelAllMemberStatusReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.DelAllMemberStatusReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=610,
  serialized_end=650,
)


_DELALLMEMBERSTATUSRSP = _descriptor.Descriptor(
  name='DelAllMemberStatusRsp',
  full_name='YOUMEServiceProtocol.DelAllMemberStatusRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.DelAllMemberStatusRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.DelAllMemberStatusRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=652,
  serialized_end=705,
)

_GETMEMBERSTATUSRSP.fields_by_name['mem_list'].message_type = _YOUMEMEMBERSTATUS
DESCRIPTOR.message_types_by_name['YoumeMemberStatus'] = _YOUMEMEMBERSTATUS
DESCRIPTOR.message_types_by_name['SetMemberStatusReq'] = _SETMEMBERSTATUSREQ
DESCRIPTOR.message_types_by_name['SetMemberStatusRsp'] = _SETMEMBERSTATUSRSP
DESCRIPTOR.message_types_by_name['GetMemberStatusReq'] = _GETMEMBERSTATUSREQ
DESCRIPTOR.message_types_by_name['GetMemberStatusRsp'] = _GETMEMBERSTATUSRSP
DESCRIPTOR.message_types_by_name['DelMemberStatusReq'] = _DELMEMBERSTATUSREQ
DESCRIPTOR.message_types_by_name['DelMemberStatusRsp'] = _DELMEMBERSTATUSRSP
DESCRIPTOR.message_types_by_name['DelAllMemberStatusReq'] = _DELALLMEMBERSTATUSREQ
DESCRIPTOR.message_types_by_name['DelAllMemberStatusRsp'] = _DELALLMEMBERSTATUSRSP

YoumeMemberStatus = _reflection.GeneratedProtocolMessageType('YoumeMemberStatus', (_message.Message,), dict(
  DESCRIPTOR = _YOUMEMEMBERSTATUS,
  __module__ = 'member_status_svr.youme_member_status_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.YoumeMemberStatus)
  ))
_sym_db.RegisterMessage(YoumeMemberStatus)

SetMemberStatusReq = _reflection.GeneratedProtocolMessageType('SetMemberStatusReq', (_message.Message,), dict(
  DESCRIPTOR = _SETMEMBERSTATUSREQ,
  __module__ = 'member_status_svr.youme_member_status_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.SetMemberStatusReq)
  ))
_sym_db.RegisterMessage(SetMemberStatusReq)

SetMemberStatusRsp = _reflection.GeneratedProtocolMessageType('SetMemberStatusRsp', (_message.Message,), dict(
  DESCRIPTOR = _SETMEMBERSTATUSRSP,
  __module__ = 'member_status_svr.youme_member_status_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.SetMemberStatusRsp)
  ))
_sym_db.RegisterMessage(SetMemberStatusRsp)

GetMemberStatusReq = _reflection.GeneratedProtocolMessageType('GetMemberStatusReq', (_message.Message,), dict(
  DESCRIPTOR = _GETMEMBERSTATUSREQ,
  __module__ = 'member_status_svr.youme_member_status_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetMemberStatusReq)
  ))
_sym_db.RegisterMessage(GetMemberStatusReq)

GetMemberStatusRsp = _reflection.GeneratedProtocolMessageType('GetMemberStatusRsp', (_message.Message,), dict(
  DESCRIPTOR = _GETMEMBERSTATUSRSP,
  __module__ = 'member_status_svr.youme_member_status_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetMemberStatusRsp)
  ))
_sym_db.RegisterMessage(GetMemberStatusRsp)

DelMemberStatusReq = _reflection.GeneratedProtocolMessageType('DelMemberStatusReq', (_message.Message,), dict(
  DESCRIPTOR = _DELMEMBERSTATUSREQ,
  __module__ = 'member_status_svr.youme_member_status_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.DelMemberStatusReq)
  ))
_sym_db.RegisterMessage(DelMemberStatusReq)

DelMemberStatusRsp = _reflection.GeneratedProtocolMessageType('DelMemberStatusRsp', (_message.Message,), dict(
  DESCRIPTOR = _DELMEMBERSTATUSRSP,
  __module__ = 'member_status_svr.youme_member_status_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.DelMemberStatusRsp)
  ))
_sym_db.RegisterMessage(DelMemberStatusRsp)

DelAllMemberStatusReq = _reflection.GeneratedProtocolMessageType('DelAllMemberStatusReq', (_message.Message,), dict(
  DESCRIPTOR = _DELALLMEMBERSTATUSREQ,
  __module__ = 'member_status_svr.youme_member_status_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.DelAllMemberStatusReq)
  ))
_sym_db.RegisterMessage(DelAllMemberStatusReq)

DelAllMemberStatusRsp = _reflection.GeneratedProtocolMessageType('DelAllMemberStatusRsp', (_message.Message,), dict(
  DESCRIPTOR = _DELALLMEMBERSTATUSRSP,
  __module__ = 'member_status_svr.youme_member_status_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.DelAllMemberStatusRsp)
  ))
_sym_db.RegisterMessage(DelAllMemberStatusRsp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
