# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kickoff_notice/youme_kickoff.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kickoff_notice/youme_kickoff.proto',
  package='YOUMEServiceProtocol',
  syntax='proto2',
  serialized_pb=_b('\n\"kickoff_notice/youme_kickoff.proto\x12\x14YOUMEServiceProtocol\"*\n\nKickOffRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\tB\x02H\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_KICKOFFRSP = _descriptor.Descriptor(
  name='KickOffRsp',
  full_name='YOUMEServiceProtocol.KickOffRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.KickOffRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='YOUMEServiceProtocol.KickOffRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['KickOffRsp'] = _KICKOFFRSP

KickOffRsp = _reflection.GeneratedProtocolMessageType('KickOffRsp', (_message.Message,), dict(
  DESCRIPTOR = _KICKOFFRSP,
  __module__ = 'kickoff_notice.youme_kickoff_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.KickOffRsp)
  ))
_sym_db.RegisterMessage(KickOffRsp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
