# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notify_svr/youme_notify.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from comm import youme_comm_pb2 as comm_dot_youme__comm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='notify_svr/youme_notify.proto',
  package='YOUMEServiceProtocol',
  syntax='proto2',
  serialized_pb=_b('\n\x1dnotify_svr/youme_notify.proto\x12\x14YOUMEServiceProtocol\x1a\x15\x63omm/youme_comm.proto\"W\n\tNotifyRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03msg\x18\x02 \x02(\t\x12,\n\x04\x61rgs\x18\x03 \x03(\x0b\x32\x1e.YOUMECommonProtocol.NameValue\"\xb8\x01\n\tNotifyReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x13\n\x0bnotify_type\x18\x02 \x02(\x05\x12\x10\n\x08snder_id\x18\x03 \x02(\x0c\x12\x11\n\trecver_id\x18\x04 \x02(\x0c\x12\x17\n\x0fnotify_property\x18\x05 \x02(\x05\x12\x12\n\nnotify_msg\x18\x06 \x01(\x0c\x12\x33\n\x0bnotify_args\x18\x07 \x03(\x0b\x32\x1e.YOUMECommonProtocol.NameValueB\x02H\x03')
  ,
  dependencies=[comm_dot_youme__comm__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NOTIFYRSP = _descriptor.Descriptor(
  name='NotifyRsp',
  full_name='YOUMEServiceProtocol.NotifyRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.NotifyRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='YOUMEServiceProtocol.NotifyRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='YOUMEServiceProtocol.NotifyRsp.args', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=165,
)


_NOTIFYREQ = _descriptor.Descriptor(
  name='NotifyReq',
  full_name='YOUMEServiceProtocol.NotifyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.NotifyReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notify_type', full_name='YOUMEServiceProtocol.NotifyReq.notify_type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='snder_id', full_name='YOUMEServiceProtocol.NotifyReq.snder_id', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recver_id', full_name='YOUMEServiceProtocol.NotifyReq.recver_id', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notify_property', full_name='YOUMEServiceProtocol.NotifyReq.notify_property', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notify_msg', full_name='YOUMEServiceProtocol.NotifyReq.notify_msg', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notify_args', full_name='YOUMEServiceProtocol.NotifyReq.notify_args', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=352,
)

_NOTIFYRSP.fields_by_name['args'].message_type = comm_dot_youme__comm__pb2._NAMEVALUE
_NOTIFYREQ.fields_by_name['notify_args'].message_type = comm_dot_youme__comm__pb2._NAMEVALUE
DESCRIPTOR.message_types_by_name['NotifyRsp'] = _NOTIFYRSP
DESCRIPTOR.message_types_by_name['NotifyReq'] = _NOTIFYREQ

NotifyRsp = _reflection.GeneratedProtocolMessageType('NotifyRsp', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYRSP,
  __module__ = 'notify_svr.youme_notify_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.NotifyRsp)
  ))
_sym_db.RegisterMessage(NotifyRsp)

NotifyReq = _reflection.GeneratedProtocolMessageType('NotifyReq', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYREQ,
  __module__ = 'notify_svr.youme_notify_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.NotifyReq)
  ))
_sym_db.RegisterMessage(NotifyReq)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
