# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_upload_token_svr/youme_upload_token.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from comm import youme_comm_pb2 as comm_dot_youme__comm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_upload_token_svr/youme_upload_token.proto',
  package='YOUMEServiceProtocol',
  syntax='proto2',
  serialized_pb=_b('\n-get_upload_token_svr/youme_upload_token.proto\x12\x14YOUMEServiceProtocol\x1a\x15\x63omm/youme_comm.proto\"^\n\x11GetUploadTokenReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x11\n\tfile_size\x18\x02 \x02(\x05\x12\x10\n\x08\x66ile_md5\x18\x03 \x02(\t\x12\x13\n\x0b\x66ile_suffix\x18\x04 \x02(\t\"\x9c\x01\n\x11GetUploadTokenRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\x12\r\n\x05token\x18\x03 \x02(\t\x12\x14\n\x0c\x64ownload_url\x18\x04 \x02(\t\x12/\n\x07headers\x18\x05 \x03(\x0b\x32\x1e.YOUMECommonProtocol.NameValue\x12\x13\n\x0b\x62ucket_type\x18\x06 \x01(\rB\x02H\x03')
  ,
  dependencies=[comm_dot_youme__comm__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETUPLOADTOKENREQ = _descriptor.Descriptor(
  name='GetUploadTokenReq',
  full_name='YOUMEServiceProtocol.GetUploadTokenReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.GetUploadTokenReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_size', full_name='YOUMEServiceProtocol.GetUploadTokenReq.file_size', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_md5', full_name='YOUMEServiceProtocol.GetUploadTokenReq.file_md5', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_suffix', full_name='YOUMEServiceProtocol.GetUploadTokenReq.file_suffix', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=188,
)


_GETUPLOADTOKENRSP = _descriptor.Descriptor(
  name='GetUploadTokenRsp',
  full_name='YOUMEServiceProtocol.GetUploadTokenRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.GetUploadTokenRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.GetUploadTokenRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='YOUMEServiceProtocol.GetUploadTokenRsp.token', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='download_url', full_name='YOUMEServiceProtocol.GetUploadTokenRsp.download_url', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='headers', full_name='YOUMEServiceProtocol.GetUploadTokenRsp.headers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bucket_type', full_name='YOUMEServiceProtocol.GetUploadTokenRsp.bucket_type', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=347,
)

_GETUPLOADTOKENRSP.fields_by_name['headers'].message_type = comm_dot_youme__comm__pb2._NAMEVALUE
DESCRIPTOR.message_types_by_name['GetUploadTokenReq'] = _GETUPLOADTOKENREQ
DESCRIPTOR.message_types_by_name['GetUploadTokenRsp'] = _GETUPLOADTOKENRSP

GetUploadTokenReq = _reflection.GeneratedProtocolMessageType('GetUploadTokenReq', (_message.Message,), dict(
  DESCRIPTOR = _GETUPLOADTOKENREQ,
  __module__ = 'get_upload_token_svr.youme_upload_token_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetUploadTokenReq)
  ))
_sym_db.RegisterMessage(GetUploadTokenReq)

GetUploadTokenRsp = _reflection.GeneratedProtocolMessageType('GetUploadTokenRsp', (_message.Message,), dict(
  DESCRIPTOR = _GETUPLOADTOKENRSP,
  __module__ = 'get_upload_token_svr.youme_upload_token_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetUploadTokenRsp)
  ))
_sym_db.RegisterMessage(GetUploadTokenRsp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
