# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room_svr/youme_room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='room_svr/youme_room.proto',
  package='YOUMEServiceProtocol',
  syntax='proto2',
  serialized_pb=_b('\n\x19room_svr/youme_room.proto\x12\x14YOUMEServiceProtocol\"0\n\x0c\x45nterRoomReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0f\n\x07room_id\x18\x02 \x02(\x0c\",\n\x0c\x45nterRoomRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\"0\n\x0cLeaveRoomReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0f\n\x07room_id\x18\x02 \x02(\x0c\",\n\x0cLeaveRoomRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\"\"\n\x0fLeaveAllRoomReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\"/\n\x0fLeaveAllRoomRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\"2\n\x0eGetRoomInfoReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0f\n\x07room_id\x18\x02 \x02(\x0c\"#\n\rYoumeRoomInfo\x12\x12\n\nmember_cnt\x18\x01 \x02(\r\"f\n\x0eGetRoomInfoRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\x12\x36\n\troom_info\x18\x03 \x02(\x0b\x32#.YOUMEServiceProtocol.YoumeRoomInfoB\x02H\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENTERROOMREQ = _descriptor.Descriptor(
  name='EnterRoomReq',
  full_name='YOUMEServiceProtocol.EnterRoomReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.EnterRoomReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='YOUMEServiceProtocol.EnterRoomReq.room_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=99,
)


_ENTERROOMRSP = _descriptor.Descriptor(
  name='EnterRoomRsp',
  full_name='YOUMEServiceProtocol.EnterRoomRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.EnterRoomRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.EnterRoomRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=145,
)


_LEAVEROOMREQ = _descriptor.Descriptor(
  name='LeaveRoomReq',
  full_name='YOUMEServiceProtocol.LeaveRoomReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.LeaveRoomReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='YOUMEServiceProtocol.LeaveRoomReq.room_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=195,
)


_LEAVEROOMRSP = _descriptor.Descriptor(
  name='LeaveRoomRsp',
  full_name='YOUMEServiceProtocol.LeaveRoomRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.LeaveRoomRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.LeaveRoomRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=241,
)


_LEAVEALLROOMREQ = _descriptor.Descriptor(
  name='LeaveAllRoomReq',
  full_name='YOUMEServiceProtocol.LeaveAllRoomReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.LeaveAllRoomReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=277,
)


_LEAVEALLROOMRSP = _descriptor.Descriptor(
  name='LeaveAllRoomRsp',
  full_name='YOUMEServiceProtocol.LeaveAllRoomRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.LeaveAllRoomRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.LeaveAllRoomRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=326,
)


_GETROOMINFOREQ = _descriptor.Descriptor(
  name='GetRoomInfoReq',
  full_name='YOUMEServiceProtocol.GetRoomInfoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.GetRoomInfoReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='YOUMEServiceProtocol.GetRoomInfoReq.room_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=378,
)


_YOUMEROOMINFO = _descriptor.Descriptor(
  name='YoumeRoomInfo',
  full_name='YOUMEServiceProtocol.YoumeRoomInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='member_cnt', full_name='YOUMEServiceProtocol.YoumeRoomInfo.member_cnt', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=415,
)


_GETROOMINFORSP = _descriptor.Descriptor(
  name='GetRoomInfoRsp',
  full_name='YOUMEServiceProtocol.GetRoomInfoRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.GetRoomInfoRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.GetRoomInfoRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_info', full_name='YOUMEServiceProtocol.GetRoomInfoRsp.room_info', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=519,
)

_GETROOMINFORSP.fields_by_name['room_info'].message_type = _YOUMEROOMINFO
DESCRIPTOR.message_types_by_name['EnterRoomReq'] = _ENTERROOMREQ
DESCRIPTOR.message_types_by_name['EnterRoomRsp'] = _ENTERROOMRSP
DESCRIPTOR.message_types_by_name['LeaveRoomReq'] = _LEAVEROOMREQ
DESCRIPTOR.message_types_by_name['LeaveRoomRsp'] = _LEAVEROOMRSP
DESCRIPTOR.message_types_by_name['LeaveAllRoomReq'] = _LEAVEALLROOMREQ
DESCRIPTOR.message_types_by_name['LeaveAllRoomRsp'] = _LEAVEALLROOMRSP
DESCRIPTOR.message_types_by_name['GetRoomInfoReq'] = _GETROOMINFOREQ
DESCRIPTOR.message_types_by_name['YoumeRoomInfo'] = _YOUMEROOMINFO
DESCRIPTOR.message_types_by_name['GetRoomInfoRsp'] = _GETROOMINFORSP

EnterRoomReq = _reflection.GeneratedProtocolMessageType('EnterRoomReq', (_message.Message,), dict(
  DESCRIPTOR = _ENTERROOMREQ,
  __module__ = 'room_svr.youme_room_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.EnterRoomReq)
  ))
_sym_db.RegisterMessage(EnterRoomReq)

EnterRoomRsp = _reflection.GeneratedProtocolMessageType('EnterRoomRsp', (_message.Message,), dict(
  DESCRIPTOR = _ENTERROOMRSP,
  __module__ = 'room_svr.youme_room_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.EnterRoomRsp)
  ))
_sym_db.RegisterMessage(EnterRoomRsp)

LeaveRoomReq = _reflection.GeneratedProtocolMessageType('LeaveRoomReq', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEROOMREQ,
  __module__ = 'room_svr.youme_room_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.LeaveRoomReq)
  ))
_sym_db.RegisterMessage(LeaveRoomReq)

LeaveRoomRsp = _reflection.GeneratedProtocolMessageType('LeaveRoomRsp', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEROOMRSP,
  __module__ = 'room_svr.youme_room_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.LeaveRoomRsp)
  ))
_sym_db.RegisterMessage(LeaveRoomRsp)

LeaveAllRoomReq = _reflection.GeneratedProtocolMessageType('LeaveAllRoomReq', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEALLROOMREQ,
  __module__ = 'room_svr.youme_room_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.LeaveAllRoomReq)
  ))
_sym_db.RegisterMessage(LeaveAllRoomReq)

LeaveAllRoomRsp = _reflection.GeneratedProtocolMessageType('LeaveAllRoomRsp', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEALLROOMRSP,
  __module__ = 'room_svr.youme_room_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.LeaveAllRoomRsp)
  ))
_sym_db.RegisterMessage(LeaveAllRoomRsp)

GetRoomInfoReq = _reflection.GeneratedProtocolMessageType('GetRoomInfoReq', (_message.Message,), dict(
  DESCRIPTOR = _GETROOMINFOREQ,
  __module__ = 'room_svr.youme_room_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetRoomInfoReq)
  ))
_sym_db.RegisterMessage(GetRoomInfoReq)

YoumeRoomInfo = _reflection.GeneratedProtocolMessageType('YoumeRoomInfo', (_message.Message,), dict(
  DESCRIPTOR = _YOUMEROOMINFO,
  __module__ = 'room_svr.youme_room_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.YoumeRoomInfo)
  ))
_sym_db.RegisterMessage(YoumeRoomInfo)

GetRoomInfoRsp = _reflection.GeneratedProtocolMessageType('GetRoomInfoRsp', (_message.Message,), dict(
  DESCRIPTOR = _GETROOMINFORSP,
  __module__ = 'room_svr.youme_room_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.GetRoomInfoRsp)
  ))
_sym_db.RegisterMessage(GetRoomInfoRsp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
