# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm_conf_svr/youme_comm_conf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from comm import youme_comm_pb2 as comm_dot_youme__comm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='comm_conf_svr/youme_comm_conf.proto',
  package='YOUMEServiceProtocol',
  syntax='proto2',
  serialized_pb=_b('\n#comm_conf_svr/youme_comm_conf.proto\x12\x14YOUMEServiceProtocol\x1a\x15\x63omm/youme_comm.proto\"\xe6\x02\n\x0b\x43ommConfReq\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0e\n\x06\x61ppkey\x18\x02 \x02(\t\x12\x0e\n\x06verify\x18\x03 \x02(\x0c\x12\x38\n\x0cservice_type\x18\x04 \x02(\x0e\x32\".YOUMEServiceProtocol.SERVICE_TYPE\x12\x35\n\x08platform\x18\x05 \x02(\x0e\x32#.YOUMECommonProtocol.DevicePlatform\x12\r\n\x05\x62rand\x18\x06 \x02(\t\x12\x13\n\x0bsys_version\x18\x07 \x02(\t\x12\x10\n\x08\x63pu_arch\x18\x08 \x02(\t\x12\x10\n\x08\x63pu_chip\x18\t \x02(\t\x12\x10\n\x08pkg_name\x18\n \x02(\t\x12\x14\n\x0c\x64\x65vice_token\x18\x0b \x02(\t\x12\r\n\x05model\x18\x0c \x02(\t\x12\x13\n\x0bsdk_version\x18\r \x02(\x05\x12\x10\n\x08sdk_name\x18\x0e \x02(\t\x12\x0f\n\x07strZone\x18\x0f \x01(\t\"\x9e\x01\n\x0b\x43ommConfRsp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0b\n\x03ret\x18\x02 \x02(\x05\x12\x10\n\x08svr_time\x18\x03 \x02(\x04\x12\r\n\x05\x61ppid\x18\x04 \x02(\x05\x12\x10\n\x08svr_addr\x18\x05 \x02(\t\x12\x10\n\x08svr_port\x18\x06 \x02(\x05\x12,\n\x04\x63onf\x18\x07 \x03(\x0b\x32\x1e.YOUMECommonProtocol.NameValue*/\n\x0cSERVICE_TYPE\x12\x0e\n\nSERVICE_IM\x10\x01\x12\x0f\n\x0bSERVICE_RTC\x10\x02\x42\x02H\x03')
  ,
  dependencies=[comm_dot_youme__comm__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SERVICE_TYPE = _descriptor.EnumDescriptor(
  name='SERVICE_TYPE',
  full_name='YOUMEServiceProtocol.SERVICE_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SERVICE_IM', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVICE_RTC', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=606,
  serialized_end=653,
)
_sym_db.RegisterEnumDescriptor(_SERVICE_TYPE)

SERVICE_TYPE = enum_type_wrapper.EnumTypeWrapper(_SERVICE_TYPE)
SERVICE_IM = 1
SERVICE_RTC = 2



_COMMCONFREQ = _descriptor.Descriptor(
  name='CommConfReq',
  full_name='YOUMEServiceProtocol.CommConfReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.CommConfReq.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appkey', full_name='YOUMEServiceProtocol.CommConfReq.appkey', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='verify', full_name='YOUMEServiceProtocol.CommConfReq.verify', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service_type', full_name='YOUMEServiceProtocol.CommConfReq.service_type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='platform', full_name='YOUMEServiceProtocol.CommConfReq.platform', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brand', full_name='YOUMEServiceProtocol.CommConfReq.brand', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sys_version', full_name='YOUMEServiceProtocol.CommConfReq.sys_version', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cpu_arch', full_name='YOUMEServiceProtocol.CommConfReq.cpu_arch', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cpu_chip', full_name='YOUMEServiceProtocol.CommConfReq.cpu_chip', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pkg_name', full_name='YOUMEServiceProtocol.CommConfReq.pkg_name', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_token', full_name='YOUMEServiceProtocol.CommConfReq.device_token', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='YOUMEServiceProtocol.CommConfReq.model', index=11,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sdk_version', full_name='YOUMEServiceProtocol.CommConfReq.sdk_version', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sdk_name', full_name='YOUMEServiceProtocol.CommConfReq.sdk_name', index=13,
      number=14, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strZone', full_name='YOUMEServiceProtocol.CommConfReq.strZone', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=443,
)


_COMMCONFRSP = _descriptor.Descriptor(
  name='CommConfRsp',
  full_name='YOUMEServiceProtocol.CommConfRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='YOUMEServiceProtocol.CommConfRsp.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret', full_name='YOUMEServiceProtocol.CommConfRsp.ret', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='svr_time', full_name='YOUMEServiceProtocol.CommConfRsp.svr_time', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appid', full_name='YOUMEServiceProtocol.CommConfRsp.appid', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='svr_addr', full_name='YOUMEServiceProtocol.CommConfRsp.svr_addr', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='svr_port', full_name='YOUMEServiceProtocol.CommConfRsp.svr_port', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='conf', full_name='YOUMEServiceProtocol.CommConfRsp.conf', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=604,
)

_COMMCONFREQ.fields_by_name['service_type'].enum_type = _SERVICE_TYPE
_COMMCONFREQ.fields_by_name['platform'].enum_type = comm_dot_youme__comm__pb2._DEVICEPLATFORM
_COMMCONFRSP.fields_by_name['conf'].message_type = comm_dot_youme__comm__pb2._NAMEVALUE
DESCRIPTOR.message_types_by_name['CommConfReq'] = _COMMCONFREQ
DESCRIPTOR.message_types_by_name['CommConfRsp'] = _COMMCONFRSP
DESCRIPTOR.enum_types_by_name['SERVICE_TYPE'] = _SERVICE_TYPE

CommConfReq = _reflection.GeneratedProtocolMessageType('CommConfReq', (_message.Message,), dict(
  DESCRIPTOR = _COMMCONFREQ,
  __module__ = 'comm_conf_svr.youme_comm_conf_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.CommConfReq)
  ))
_sym_db.RegisterMessage(CommConfReq)

CommConfRsp = _reflection.GeneratedProtocolMessageType('CommConfRsp', (_message.Message,), dict(
  DESCRIPTOR = _COMMCONFRSP,
  __module__ = 'comm_conf_svr.youme_comm_conf_pb2'
  # @@protoc_insertion_point(class_scope:YOUMEServiceProtocol.CommConfRsp)
  ))
_sym_db.RegisterMessage(CommConfRsp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
