# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm/youme_comm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comm/youme_comm.proto',
  package='YOUMECommonProtocol',
  syntax='proto2',
  serialized_pb=_b('\n\x15\x63omm/youme_comm.proto\x12\x13YOUMECommonProtocol\"]\n\tNameValue\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x12\x33\n\nvalue_type\x18\x03 \x02(\x0e\x32\x1f.YOUMECommonProtocol.VALUE_TYPE\"=\n\nMsgComment\x12/\n\x07\x63omment\x18\x01 \x03(\x0b\x32\x1e.YOUMECommonProtocol.NameValue*\xa6\x01\n\nVALUE_TYPE\x12\x10\n\x0cVALUE_UNKNOW\x10\x00\x12\x0f\n\x0bVALUE_INT32\x10\x01\x12\x0f\n\x0bVALUE_UIN32\x10\x02\x12\x0f\n\x0bVALUE_INT64\x10\x03\x12\x10\n\x0cVALUE_UINT64\x10\x04\x12\x10\n\x0cVALUE_STRING\x10\x05\x12\x0f\n\x0bVALUE_BYTES\x10\x06\x12\x0e\n\nVALUE_BOOL\x10\x07\x12\x0e\n\nVALUE_BLOB\x10\x08*\x89\x01\n\x0e\x44\x65vicePlatform\x12\x13\n\x0fPlatform_Unknow\x10\x00\x12\x14\n\x10Platform_Android\x10\x01\x12\x10\n\x0cPlatform_IOS\x10\x02\x12\x14\n\x10Platform_Windows\x10\x03\x12\x10\n\x0cPlatform_OSX\x10\x04\x12\x12\n\x0ePlatform_Linux\x10\x05*y\n\rDistrictLevel\x12\x14\n\x10\x44ISTRICT_COUNTRY\x10\x01\x12\x15\n\x11\x44ISTRICT_PROVINCE\x10\x02\x12\x11\n\rDISTRICT_CITY\x10\x03\x12\x13\n\x0f\x44ISTRICT_COUNTY\x10\x04\x12\x13\n\x0f\x44ISTRICT_STREET\x10\x05\x42\x02H\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_VALUE_TYPE = _descriptor.EnumDescriptor(
  name='VALUE_TYPE',
  full_name='YOUMECommonProtocol.VALUE_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VALUE_UNKNOW', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_INT32', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_UIN32', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_INT64', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_UINT64', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_STRING', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_BYTES', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_BOOL', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VALUE_BLOB', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=205,
  serialized_end=371,
)
_sym_db.RegisterEnumDescriptor(_VALUE_TYPE)

VALUE_TYPE = enum_type_wrapper.EnumTypeWrapper(_VALUE_TYPE)
_DEVICEPLATFORM = _descriptor.EnumDescriptor(
  name='DevicePlatform',
  full_name='YOUMECommonProtocol.DevicePlatform',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Platform_Unknow', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Platform_Android', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Platform_IOS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Platform_Windows', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Platform_OSX', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Platform_Linux', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=374,
  serialized_end=511,
)
_sym_db.RegisterEnumDescriptor(_DEVICEPLATFORM)

DevicePlatform = enum_type_wrapper.EnumTypeWrapper(_DEVICEPLATFORM)
_DISTRICTLEVEL = _descriptor.EnumDescriptor(
  name='DistrictLevel',
  full_name='YOUMECommonProtocol.DistrictLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISTRICT_COUNTRY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISTRICT_PROVINCE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISTRICT_CITY', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISTRICT_COUNTY', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISTRICT_STREET', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=513,
  serialized_end=634,
)
_sym_db.RegisterEnumDescriptor(_DISTRICTLEVEL)

DistrictLevel = enum_type_wrapper.EnumTypeWrapper(_DISTRICTLEVEL)
VALUE_UNKNOW = 0
VALUE_INT32 = 1
VALUE_UIN32 = 2
VALUE_INT64 = 3
VALUE_UINT64 = 4
VALUE_STRING = 5
VALUE_BYTES = 6
VALUE_BOOL = 7
VALUE_BLOB = 8
Platform_Unknow = 0
Platform_Android = 1
Platform_IOS = 2
Platform_Windows = 3
Platform_OSX = 4
Platform_Linux = 5
DISTRICT_COUNTRY = 1
DISTRICT_PROVINCE = 2
DISTRICT_CITY = 3
DISTRICT_COUNTY = 4
DISTRICT_STREET = 5



_NAMEVALUE = _descriptor.Descriptor(
  name='NameValue',
  full_name='YOUMECommonProtocol.NameValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='YOUMECommonProtocol.NameValue.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='YOUMECommonProtocol.NameValue.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_type', full_name='YOUMECommonProtocol.NameValue.value_type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=139,
)


_MSGCOMMENT = _descriptor.Descriptor(
  name='MsgComment',
  full_name='YOUMECommonProtocol.MsgComment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='comment', full_name='YOUMECommonProtocol.MsgComment.comment', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=202,
)

_NAMEVALUE.fields_by_name['value_type'].enum_type = _VALUE_TYPE
_MSGCOMMENT.fields_by_name['comment'].message_type = _NAMEVALUE
DESCRIPTOR.message_types_by_name['NameValue'] = _NAMEVALUE
DESCRIPTOR.message_types_by_name['MsgComment'] = _MSGCOMMENT
DESCRIPTOR.enum_types_by_name['VALUE_TYPE'] = _VALUE_TYPE
DESCRIPTOR.enum_types_by_name['DevicePlatform'] = _DEVICEPLATFORM
DESCRIPTOR.enum_types_by_name['DistrictLevel'] = _DISTRICTLEVEL

NameValue = _reflection.GeneratedProtocolMessageType('NameValue', (_message.Message,), dict(
  DESCRIPTOR = _NAMEVALUE,
  __module__ = 'comm.youme_comm_pb2'
  # @@protoc_insertion_point(class_scope:YOUMECommonProtocol.NameValue)
  ))
_sym_db.RegisterMessage(NameValue)

MsgComment = _reflection.GeneratedProtocolMessageType('MsgComment', (_message.Message,), dict(
  DESCRIPTOR = _MSGCOMMENT,
  __module__ = 'comm.youme_comm_pb2'
  # @@protoc_insertion_point(class_scope:YOUMECommonProtocol.MsgComment)
  ))
_sym_db.RegisterMessage(MsgComment)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
